### ISSUE TITLE
Pixmap icon is not installed correctly

### ISSUE THREAD

**Issue by mmetak** [PhotoFlare/photoflare#101]
When I build the latest git package it installs it in `/tmp/...`

https://github.com/PhotoFlare/photoflare/blob/9a4288893a4a15adee217f2272a7ba80635da569/PhotoFlare.pro#L233

to this: `pixmaps.path = $${BASEDIR}$${PREFIX}/share/pixmaps/`

**Comment by DylanC** [comment]
@mmetak - Thanks. I have this updated now with this commit - 4802ccd558d8f99db94b0bc8fbb4920a2f4c95ca. Can you give it a try?
