### ISSUE TITLE
High resolution image artifacts

### ISSUE THREAD

**Issue by Kantrast** [PhotoFlare/photoflare#103]
Summary: Some of high resolution images are displayed with artifacts using zoom 
Component: UI
Severity: Minor.
Platform: Windows 10.
Steps to reproduce:

1. Start program.
2. Click "open" button.
3. Add a high resolution image (4k or higher).
4. Set zoom to any mark except 100%.

Result: Image with artifacts.
Expected result: Clean image.
Attachment: [photoflare](https://user-images.githubusercontent.com/42489023/44299045-9dfdd200-a318-11e8-8407-ef17d9f7f544.jpg)

**Comment by DylanC** [comment]
@Kantrast - I have tested with 4k images before without issues. This image you are testing with is producing a problem though. I just need to figure it out.

**Comment by Kantrast** [comment]
Unfortunately I cannot detect a factor which triggers the bug. Some of the images of equal characteristics cause this problem and some did not.

**Comment by DylanC** [comment]
@Kantrast - I have this improved now but still its not a "clean image". Still trying to figure out the cause of this.

**Comment by DylanC** [comment]
@Kantrast - I think this is due to how the image is scaled. I noticed the original PhotoFiltre on Windows also has the same issue with this image.
