### ISSUE TITLE
Lack of a performance on resolutions 1920x1080 and higher. 

### ISSUE THREAD

**Issue by Kantrast** [PhotoFlare/photoflare#105]
Summary: Experience a lack of a performance working with high resolution images (1920x1080 and higher)
Component: Performance.
Severity: Major.
Platform: Windows 10.
Steps to reproduce:
1. Start program.
2. Open/create an image of full hd resolution or higher.
3. Apply any tools.

Result: Lack of performance.
Expected result: Good performance
Attachment: [performance_bug.zip](https://github.com/PhotoFlare/photoflare/files/2299725/performance_bug.zip)

**Comment by glaubersm** [comment]
Performance is bad on linux too.

**Comment by DylanC** [comment]
@Kantrast @glaubersm - Due to some investigations recently I think this is due to the undo/redo system. This is now going to be rewritten in the Studio version. Feature may be backported to the Community Edition in the future too. :+1:

**Comment by DylanC** [comment]
@Kantrast @glaubersm - v1.6.0 has been released with multi threading support. A big improvement on performance should be noticed.
