### ISSUE TITLE
The problem of restoring the brush option panel

### ISSUE THREAD

**Issue by SecurityAdmin** [PhotoFlare/photoflare#107]
Summary: You can not call the brush options panel after closing.
Component: Toolpalette.
Severity: Trivial.
Platform: Windows 10.
Steps to reproduce:
1.Start program.
2.Click "close" Brush Options.
Result: Brush options panel after closed. You can not call the brush options panel after closing.
[Brush Options.zip](https://github.com/PhotoFlare/photoflare/files/2299980/Brush.Options.zip)

**Comment by DylanC** [comment]
@SecurityAdmin - Thanks, confirming as a bug.

**Comment by DylanC** [comment]
@SecurityAdmin - I have a fix pushed in for this. Those panels are no longer able to close or float which is now correct. This fix will be in the next release.
