### ISSUE TITLE
Scanner connection error message

### ISSUE THREAD

**Issue by SecurityAdmin** [PhotoFlare/photoflare#108]
Summary: No message to the user that the scanner is not connected.
Component: Scan.
Severity: Trivial.
Platform: Windows 10.
Steps to reproduce:
Start program.
1.Click "Scan" button.
2.Click "Acquire image..." button.
Result: Untitled Window.
3.Click "Select source..." button.
Result: No result.
Expected Result:A message to the user that the scanner is not connected. 
[Scanner connection.zip](https://github.com/PhotoFlare/photoflare/files/2299981/Scanner.connection.zip)

**Comment by DylanC** [comment]
@SecurityAdmin - Thanks but in the v1.5.4 release the scanning feature has already been removed for having too much problems and to help packaging for Debian official repository.
