### ISSUE TITLE
Problem with Select All on high-resolution images

### ISSUE THREAD

**Issue by SecurityAdmin** [PhotoFlare/photoflare#109]
Summary: High resolution image is not allocated.
Component: Select All.
Severity: Major.
Platform: Windows 10.
Steps to reproduce:
1.Start program.
2.Click "open" button.
3.Open an image with a higher resolution.
4.Select All.
Result: No image selected.
Expected Result:High resolution image selection.
[Select All.zip](https://github.com/PhotoFlare/photoflare/files/2299982/Select.All.zip)

**Comment by DylanC** [comment]
Cannot reproduce this issue. I can select all with 4K resolution images no problem.
