### ISSUE TITLE
The program settings can only be canceled after a reboot.

### ISSUE THREAD

**Issue by SecurityAdmin** [PhotoFlare/photoflare#110]
Summary: The default settings are set after the program is restarted.
Component: Preferences.
Severity: Minor.
Platform: Windows 10.
Steps to reproduce:
1.Start program.
2.Set the program settings.
3.Click "Ok".
4.Restart the program.
5.Select the preferences tab.
6.Click "Cancel".
7.Restart the program.
Result: Program settings are set by default.
Expected Result: When you click the Cancel button, the settings are set by default in the current program session.
[Preferences.zip](https://github.com/PhotoFlare/photoflare/files/2299984/Preferences.zip)

**Comment by DylanC** [comment]
@SecurityAdmin - Do you think this is related to #43?

**Comment by DylanC** [comment]
@SecurityAdmin - Fix pushed in for this. Thanks.
