### ISSUE TITLE
"Full Screen" mode freezes the program window.

### ISSUE THREAD

**Issue by SecurityAdmin** [PhotoFlare/photoflare#114]
Summary:Enabling the "Full Screen" mode causes the program window to hang after it is restarted.
Severity: Trivial.
Platform: Windows 10.
Steps to reproduce:
1.Start program.
2.Click "View".
3.Click "Full Screen".
4.Restart the program.
5."Full Screen" mode is active.
6.Reset the "Full Screen".
Result: Managing the size of the window is obtained only after the program is restarted.
Expected Result:Run the program only in normal mode (not "Full Screen").
[Full Screen.zip](https://github.com/PhotoFlare/photoflare/files/2299990/Full.Screen.zip)

**Comment by DylanC** [comment]
@SecurityAdmin - This has been fixed in #93
