### ISSUE TITLE
Displaying the Software Version.

### ISSUE THREAD

**Issue by SecurityAdmin** [PhotoFlare/photoflare#115]
Summary:The version of the program is not displayed in the "Applications and Features" panel of Windows 10.
The version of the program is not displayed in the properties of the PhotoFlare.exe file.
Severity: Trivial.
Platform: Windows 10.
Steps to reproduce:
Expected Result:Displaying the Software Version.
[Displaying the Software Version.zip](https://github.com/PhotoFlare/photoflare/files/2299991/Displaying.the.Software.Version.zip)

**Comment by DylanC** [comment]
@SecurityAdmin - I tried to fix this for v1.5.5 but I couldn't figure it out. I will work on this again for the next release.

**Comment by DylanC** [comment]
@SecurityAdmin - Fixed for v1.5.6.1. Thanks.
