### ISSUE TITLE
There is no background information for the user.

### ISSUE THREAD

**Issue by SecurityAdmin** [PhotoFlare/photoflare#116]
Summary: There is no help information about the software product. Calling help does not work.
There is no tooltip with the name of the tool type "Brush" when you hover the pointer "mouse".
Severity: Trivial.
Platform: Windows 10.
Expected Result: Availability of reference information.

**Comment by DylanC** [comment]
@SecurityAdmin - Do you have a screenshot to show me what you mean?

**Comment by SecurityAdmin** [comment]
Hello. The context help is not available. As an example ...
[Help_example.zip](https://github.com/PhotoFlare/photoflare/files/2303467/Help_example.zip)

**Comment by SecurityAdmin** [comment]
When you click "?" A help message is expected.
[help_message.zip](https://github.com/PhotoFlare/photoflare/files/2303470/help_message.zip)

**Comment by SecurityAdmin** [comment]
Missing tooltip when hovering mouse over the panel icon "Brushes".
[icon_Brushes.zip](https://github.com/PhotoFlare/photoflare/files/2303472/icon_Brushes.zip)

**Comment by DylanC** [comment]
@SecurityAdmin - I will respond to your comments with numbers:

1. Ah, so you want an offline software manual to be available. I could do this but I need to spend time writing the manual first. We do have this online but its very small - http://photoflare.io/documentation/.
2. This has been resolved in #91.
3. Good idea! I will fix this.

**Comment by DylanC** [comment]
@SecurityAdmin - Added the tooltips. Can you open a new item for the "Offline Documentation" feature?
