### ISSUE TITLE
Menu interface "View".

### ISSUE THREAD

**Issue by SecurityAdmin** [PhotoFlare/photoflare#117]
Summary: A flag is not selected when selecting menu items "View" ("Filter Bar", "Tool Palette", "Full Screen", "Show Grid").
Severity: Trivial.
Platform: Windows 10.
Expected Result:Perfected interface menu "View".

**Comment by DylanC** [comment]
@SecurityAdmin - This has been fixed in the latest code and will be in the next release. Thanks.
