### ISSUE TITLE
"Auto levels" feature crushes an image.

### ISSUE THREAD

**Issue by Kantrast** [PhotoFlare/photoflare#118]
Summary: "Auto levels" feature makes colors unnatural and generates artifacts.
Component: Adjustments.
Severity: Major.
Platform: Windows 10.
Steps to reproduce:

1. Start program.
2. Click "open" button.
3. Select a file.
4. Apply "auto levels".

Result: Unnatural colors and artifacts.
Expected result: Better brightness or/and contrast or/and saturation.
Attachment: [Auto_levels_bug.zip](https://github.com/PhotoFlare/photoflare/files/2300404/Auto_levels_bug.zip)

**Comment by DylanC** [comment]
@Kantrast - Does it generate artifacts with all images you tried?

**Comment by Kantrast** [comment]
@DylanC I rechecked and I would say it happens with the most part of images espessially photos. Problems I see: loss of clarity, colorful pixels, noise, unnatural colors. They can rise together or 
separately. I can make a video for you :-)

**Comment by DylanC** [comment]
@Kantrast - We just use a standard feature from graphicsmagick library.
http://www.graphicsmagick.org/Magick++/Image.html#equalize

Seems to work as expected on the images I've been testing. Its not really supposed to improve those values you mentioned. It just returns the image colours back to the original values.
https://en.wikipedia.org/wiki/Histogram_equalization
