### ISSUE TITLE
Navigation tools don't allow to move up and left on an increased image.

### ISSUE THREAD

**Issue by Kantrast** [PhotoFlare/photoflare#121]
Summary: Navigation sliders cannot move up and left on an increased image.
Component: UI.
Severity: Major.
Platform: Windows 10.
Steps to reproduce:

1. Start the program.
2. Open/create an image.
3. Use zoom to make an image bigger than visible work area.
4. Try to move navigation sliders up/left 

Result: Navigation sliders move only in up/right directions.
Expected result: Possibility to reach up and left sides of an image after its increase.
Attachment:[navigation_problem.zip](https://github.com/PhotoFlare/photoflare/files/2300463/navigation_problem.zip)

**Comment by DylanC** [comment]
@Kantrast - Good find. Thanks!
