### ISSUE TITLE
The problem of setting the parameters of the meters of the canvas image.

### ISSUE THREAD

**Issue by SecurityAdmin** [PhotoFlare/photoflare#122]
Summary:You can not change the canvas settings again.
Severity: Major.
Platform: Windows 10.
Steps to reproduce:
1.Start program.
2.Open an image.
3.Click "Canvas size".
4.Set the parameters of the canvas.
5.We change the installed parameters of the canvas.
Result: Can not change canvas settings.
Expected Result:Changing the image parameter of the image canvas.
[Canvas size.zip](https://github.com/PhotoFlare/photoflare/files/2300594/Canvas.size.zip)

**Comment by DylanC** [comment]
@SecurityAdmin - I'm not sure if this is a bug. You didn't change the canvas size in the dialog. If you do change it you would see the new coloured canvas on the screen.

**Comment by SecurityAdmin** [comment]
I agree, this is not a bug. I'm sorry.
