### ISSUE TITLE
The issue with "recent files" menu item

### ISSUE THREAD

**Issue by NeroLocker** [PhotoFlare/photoflare#126]
Summary: There is a way to open nonexistent image using menu "recent files". When you try to save one on hard rive, an error "unable to save image" occurs.
Operating system: Windows 10 Pro x64.
Program version: 1.5.3 Community Edition.

Steps to reproduce issue:
1.Start the program;
2.Make new image;
3.Save image on disk and close it;
4.Delete this image file from disk;
5.Open last image using "recent files" menu item.
6.Try to "save as.." opened image to new location.

Result: Error "unable to save image" occurs, Image has zero size.
Expected behaviour: When someone try to open nonexistent image using menu, show warning there isn't image file on disk to open.

[error.zip](https://github.com/PhotoFlare/photoflare/files/2300797/error.zip)

**Comment by DylanC** [comment]
@NeroLocker - Hello, The Recent Files menu has a cool feature where it rebuilds the menu on next program launch. Only files that exist on disk stay on the Recent Files menu. However, I do also think we need to check if the file exists before the user restarts the program. Good idea!

**Comment by NeroLocker** [comment]
@DylanC well. Thanks for the detailed answer!

**Comment by DylanC** [comment]
@NeroLocker - Pushed in a fix with the message "Image does not exist at this file path" if the image does not exist.
