### ISSUE TITLE
Automatic change height/width values of image to maximum when resolution is 0

### ISSUE THREAD

**Issue by NeroLocker** [PhotoFlare/photoflare#127]
Summary: The height and width values in the image creation window jump suddenly to the maximum when the resolution field is 0.
Operating system: Windows 10 Pro x64.
Program version: 1.5.3 Community Edition.

Steps to reproduce issue:
1.Start the program;
2.Open creation image menu and change pixels type to cm or inches.
3.Set the resolution to 0.

Result: The height and width changes values.
Expected behaviour: Inability to set a zero value of resolution.

[h w values.zip](https://github.com/PhotoFlare/photoflare/files/2301017/h.w.values.zip)

**Comment by DylanC** [comment]
@NeroLocker - Confirmed as a bug. Thanks!
