### ISSUE TITLE
Ability to create an empty image

### ISSUE THREAD

**Issue by NeroLocker** [PhotoFlare/photoflare#128]
Summary: When creating a new image, the height and width values can be zero. This image with zero sizes can not be saved and It makes no sense.
Operating system: Windows 10 Pro x64.
Program version: 1.5.3 Community Edition.

Steps to reproduce issue:
1.Start the program;
2.Open creation image menu and set height/width values to 0;
3.Try to save image.

Result: Error "unable to save image" occurs.
Expected behaviour: Inability to set a zero value of h/w.

[h w issue.zip](https://github.com/PhotoFlare/photoflare/files/2301076/h.w.issue.zip)

**Comment by DylanC** [comment]
@NeroLocker - Thanks for the report, already fixed. :)  246ef4d906c17918d96a84ca0d6627ba0dd7fd75
