### ISSUE TITLE
when the image is not loaded "ctr + u" closes the program

### ISSUE THREAD

**Issue by Sugakusha** [PhotoFlare/photoflare#130]
when you open the program and you press "ctr + u" = duplicate, programm closes
step to reproduce:
1)open programm 
2)press "ctr + u"  or image->duplicate

result: programm closes
Expected behaviour: program continues to work

Operating system: Windows 7 x64.
Program version: 1.5.3 Community Edition.

**Comment by DylanC** [comment]
@Sugakusha - Dup of #124. This has already been fixed and the fix will be in the next release. (v1.5.5)
