### ISSUE TITLE
The program crashes when you press a button "Show Grid..."

### ISSUE THREAD

**Issue by Apokefal** [PhotoFlare/photoflare#136]
Summary: When you click on the button "Show Grid...", the program will close.
Operating system: Windows 7 Ultimate x64.
Program version: 1.5.5 Community Edition.

Steps to reproduce issue:
1.Start the program;
2.View View -> Show Grid ...

**Comment by DylanC** [comment]
@Apokefal - Thanks, pushed a fix for this.
