### ISSUE TITLE
Maximum consumption of computer resources when the program hangs

### ISSUE THREAD

**Issue by Apokefal** [PhotoFlare/photoflare#137]
Summary: When the program hangs, it starts loading the system, taking about 14GB of RAM
Operating system: Windows 10 Pro x64.
Program version: 1.5.5 Community Edition.

Steps to reproduce issue:
1.Start the program;
2.Create a new document
3.View View->Show Grid ...->Set the value to 0->Ok
Result: The program hangs, the load on the system RAM begins.
<a href="https://ibb.co/bQGoip"><img src="https://preview.ibb.co/cw8epU/Screenshot_2.png" alt="Screenshot_2" border="0"></a>

**Comment by DylanC** [comment]
@Apokefal - Fixed. Thanks.
