### ISSUE TITLE
When unplugging the Toolpalette, it is not possible to reattach it to the window

### ISSUE THREAD

**Issue by Apokefal** [PhotoFlare/photoflare#139]
Summary: You need to unfasten the toolpalette, and try to attach it back
Operating system: Windows 7 Ultimate x64.
Program version: 1.5.5 Community Edition.

Steps to reproduce issue:
1.Start the program;
2.Unpin and close Toolpalette
3.Unpin and close Settings Toolpalette
4.Click ctrl+L, Try to attach the toolpalette to the window

**Comment by DylanC** [comment]
@Apokefal - I have a fix pushed in for this. Those panels are no longer able to close or float which is now correct. This fix will be in the next release.
