### ISSUE TITLE
PhotoFlare incompatible 32bit

### ISSUE THREAD

**Issue by abuhenasobuj** [PhotoFlare/photoflare#14]
# PhotoFiltreLX-STU_1.2 is incompatible on Windows 10 (32 bit) Machine.
```
Program Compatibility Troubleshooter
Issues found
Incompatible Program Detected
Fix program PhotoFiltreLX-STU_1.2 Completed
Issues found
Incompatible Program Detected
PhotoFiltreLX-STU_1.2 is incompatible.
Fix program PhotoFiltreLX-STU_1.2 Completed
Provides steps to fix the incompatible program.
Compatibility Mode
Compabitiliy modes applied:
```

_Windows Version: 10.0
Architecture: x86_

**Comment by DylanC** [comment]
Hello, 

Yes, Studio 1.2 does not have a 32bit build for Windows machines at the moment. I can work on this in the future but at the moment 32bit support is low priority.

Kind regards,
D.

**Comment by abuhenasobuj** [comment]
I/(we)'ll be glad if is there available an 32 bit environment supported version.
