### ISSUE TITLE
There is no option to open the Toolpalette setting after closing

### ISSUE THREAD

**Issue by Apokefal** [PhotoFlare/photoflare#140]
Summary: There is no option to open the Toolpalette setting after closing
Operating system: Windows 7 Ultimate x64.
Program version: 1.5.5 Community Edition.

Steps to reproduce issue:
1.Start the program;
2.Close toolbar setup

**Comment by DylanC** [comment]
Dup of #107

**Comment by DylanC** [comment]
@Apokefal - I have a fix pushed in for this. Those panels are no longer able to close or float which is now correct. This fix will be in the next release.
