### ISSUE TITLE
The text on the button does not fit completely

### ISSUE THREAD

**Issue by Apokefal** [PhotoFlare/photoflare#141]
Summary: If you select the Dutch language and restart the program, and again try to change the language, we will see that the button "Restart the program" will have a long name
Operating system: Windows 7 Ultimate x64. 
Program version: 1.5.5 Community Edition.

Steps to reproduce issue:
1.Start the program;
2.Tools>>Preferences>>Startup 
3.Select the Dutch language>>Click "Restart to apply"
4.Gereedschappen>>Voorkeuren>>Opstarten
5.Select random language
Result
![screenshot_3](https://user-images.githubusercontent.com/39430990/46675305-5274ef80-cc08-11e8-81a1-3087278399cb.png)

**Comment by DylanC** [comment]
@Apokefal - Pushed in a fix for this. Thanks.
