### ISSUE TITLE
 'Gamma correct' ('+' or '-') makes the image black

### ISSUE THREAD

**Issue by Maxitestr** [PhotoFlare/photoflare#143]
Operating system: windows 10 enterprise 2016 x 64
Program version: PhotoFlare_CE_1.5.5_amd64_win_r2
Image size (1920x1200)

1. start the program;
2. open the file .jpeg;
3. use 'gamma correct' '+' or '-' on the toolbar;

![gamma](https://user-images.githubusercontent.com/44970437/48355404-82f7ef80-e6c6-11e8-80d0-8e43e31e23ad.png)

**Comment by DylanC** [comment]
@Maxitestr - Pushed in a fix for this today. It will be in the next release. Thanks.
