### ISSUE TITLE
 file does not open after changing format via rename to Windows

### ISSUE THREAD

**Issue by Maxitestr** [PhotoFlare/photoflare#144]
Operating system: windows 10 enterprise 2016 x 64
Program version: PhotoFlare_CE_1.5.5_amd64_win_r2

preparatory actions: change the format of the .jpg file to .gif by renaming Windows.
1. open program;
2. use file/open
3. open the prepared file

Expected result: file opened
Actual result: the file does not open, an error window appears

**Comment by Maxitestr** [comment]
![form](https://user-images.githubusercontent.com/44970437/48362588-8abf9000-e6d6-11e8-9d5d-cd9db277a920.png)

**Comment by DylanC** [comment]
@Maxitestr - Pushed in a fix to show an option to rename the file extension on file open. Will be available in the next release.
