### ISSUE TITLE
[Windows 10] blur bug 

### ISSUE THREAD

**Issue by soflanchig** [PhotoFlare/photoflare#145]
1.	Open PhotoFlare  v1.5.5.
2.	File – New – 1920х1080
![1](https://user-images.githubusercontent.com/44993160/48393472-51bd0500-e742-11e8-8d98-36ef41ef7f79.png)
3.	RGB mode 
4.	3 lines «pain brush» 
 
![2](https://user-images.githubusercontent.com/44993160/48393487-60a3b780-e742-11e8-91f1-df7c5e2193d3.png)

5.	Button «indexed mode»
6.	Button «Transparent Colour» - Tolerance «20» - ок 
7.	 
![3](https://user-images.githubusercontent.com/44993160/48393490-64373e80-e742-11e8-8970-401762092e30.png)

8.	«Paint Bucket» - White background 
 
![4](https://user-images.githubusercontent.com/44993160/48393494-67cac580-e742-11e8-803e-2fba2ac04ac1.png)

9.	tap Button «Blur» 
10.	 
![5](https://user-images.githubusercontent.com/44993160/48393499-6e593d00-e742-11e8-990c-6ac392613bba.png)

11.	Bug 
 
![6](https://user-images.githubusercontent.com/44993160/48393506-71ecc400-e742-11e8-841b-57c6dbb70f77.png)

**Comment by DylanC** [comment]
@soflanchig - Blur works fine normally. Is there a reason to be switching to indexed mode?
