### ISSUE TITLE
Advanced paint brush doesn't draw with a singular left click

### ISSUE THREAD

**Issue by 70xx00** [PhotoFlare/photoflare#146]
"Advanced paint brush" stencils doesn't draw by once left mouse button click.
Severity: Trivial.
Platform: Windows 10.
Steps to reproduce:
1. Run the program.
2. Click the button "Advanced paint brush"
3. Choose one of the stencils in a dropdown menu
4. Try to draw by once left mouse button click

Result: The stencils doesn't draw

**Comment by DylanC** [comment]
@70xx00 - Confirmed.

**Comment by DylanC** [comment]
@70xx00 - I have added a fix for this tonight. It will be in the next release.
