### ISSUE TITLE
File .mng does not open on Windows

### ISSUE THREAD

**Issue by PrMary** [PhotoFlare/photoflare#148]
Operating system: windows 10 home 2018 x 64

1. open program;
2. open the prepared file

Actual result: "Please open a valid image file"

**Comment by DylanC** [comment]
@PrMary - This format is not currently supported. We support Qt default format types so far.
http://doc.qt.io/qt-5/qimagereader.html#supportedImageFormats

**Comment by DylanC** [comment]
@PrMary - Oh apologies, I think Windows build might be missing a library for this.

**Comment by DylanC** [comment]
@PrMary - Windows seems to have all the libraries but yet it doesn't work. Treating this as a bug. However, .mng does open on the Linux version.

**Comment by DylanC** [comment]
Tested as working on Windows 10. PhotoFlare 1.6.7 dev build.
