### ISSUE TITLE
File .tga does not open

### ISSUE THREAD

**Issue by PrMary** [PhotoFlare/photoflare#149]
Operating system: windows 10 home 2018 x 64

1. open program;
2. open the prepared file;
3. add change
4. save this change
5. close file
6. repeatedly open this file

Actual result: "Please open a valid image file"

**Comment by DylanC** [comment]
@PrMary - Same reason as #148 I think. Will fix this for the next release.

**Comment by DylanC** [comment]
@PrMary - This seems to happen on Linux and Windows. We follow the Qt supported formats here:
http://doc.qt.io/qt-5/qtimageformats-index.html

It should have read support according to the documentation but it doesn't seem to work on either platform right now.

**Comment by DylanC** [comment]
Tested as working on Windows 10. PhotoFlare 1.6.7 dev build.
