### ISSUE TITLE
'Contrast correct' ('+' or '-') makes the image only more contrast

### ISSUE THREAD

**Issue by BaranovAleksandr** [PhotoFlare/photoflare#151]
Operating system: windows 7 x 64
Program version: PhotoFlare-CE_1.5.5_amd64_win_r2.msi
Image size (1920x1200)

Steps to reproduce issue:
1. Start the program;
2. Open the file .png;
3. Use 'Contrast correct' '+' or '-' on the toolbar;

![default](https://user-images.githubusercontent.com/45045411/48501843-c2fad600-e870-11e8-9b9a-8efbcd72580e.png)

**Comment by DylanC** [comment]
@BaranovAleksandr - We have a newer version of graphicsmagick. I think the lib now works differently and the code will need to be adjusted for the next version. Thanks.

**Comment by DylanC** [comment]
@BaranovAleksandr - Pushed in a fix for this. Thanks. It will be in the next release.
