### ISSUE TITLE
Auto Zoom does not work

### ISSUE THREAD

**Issue by BaranovAleksandr** [PhotoFlare/photoflare#154]
Operating system: windows 7 x 64
Program version: PhotoFlare-CE_1.5.5_amd64_win_r2.msi

Image size (1920x1200)

Steps to reproduce issue:
1. Start the program;
2. Create a new document
3. Click View->Auto Zoom (Make sure the zoom is not working.)

**Comment by DylanC** [comment]
@BaranovAleksandr - This option has been removed. It shouldn't really be available in the frontend. Closing this issue now. Thanks.
