### ISSUE TITLE
Program crash when using colour threshold on picture with some resolution

### ISSUE THREAD

**Issue by LoveRider** [PhotoFlare/photoflare#155]
Operating system: Windows 10 Pro
Program version: PhotoFlare_CE_1.5.5_amd64_win_r2
Images size (690x298, 320x240, maybe more)

Steps to reproduce issue:
1. Run the program.
2. Open file.
3. Filter -> Colour -> Colour Threshold.

Result: program crushes. 
I opened JPEG-files with a resolution 690x298 and a resolution 320x240.

**Comment by LoveRider** [comment]
@DylanC - The program just closes.

**Comment by DylanC** [comment]
@LoveRider - Hmm.. I tested this and it doesn't happen for me. I will try it with smaller images.
