### ISSUE TITLE
Paint brush starts painting only after changing the parameters.

### ISSUE THREAD

**Issue by LoveRider** [PhotoFlare/photoflare#156]
Operating system: Windows 10 Pro
Program version: PhotoFlare_CE_1.5.5_amd64_win_r2
Image size (1920x1080)

Steps to reproduce issue:
1.	Run the program.
2.	Open file.
3.	Click the button "Paint brush".
4.	Try to draw something.

Result: Brush doesn’t draw.

This bug disappears after changing the brush parameters (radius, pressure) and appears only after the application is restarted.

**Comment by DylanC** [comment]
@LoveRider - I see. The problem was down to the default opacity/pressure not being set. I have a fix put in for the next release. Thanks.
