### ISSUE TITLE
Copy bug

### ISSUE THREAD

**Issue by LoveRider** [PhotoFlare/photoflare#157]
Operating system: Windows 10 Pro
Program version: PhotoFlare_CE_1.5.5_amd64_win_r2
Image size (1920x1080)

Steps to reproduce issue:
1.	Run the program.
2.	Open file.
3.	Make some changes, for example, add text.
4.	Make a copy.
5.	Paste a copy.
6.	Undo any changes.
7.	Hold LMB and try to move picture.

Result: а copy will appear again.

**Comment by DylanC** [comment]
@LoveRider - I tried this and it didn't work. Any advice on how to produce this issue?
