### ISSUE TITLE
Paste As New Image doesn't work as expected

### ISSUE THREAD

**Issue by PolkinaAA** [PhotoFlare/photoflare#161]
Operating system: Windows 10 x64
Program version: PhotoFlare v1.5.5

1. Open the program
2. Open image
3. Selection area
4. Click "Copy"
5. Click "Paste As New Image"
6. Image is copied entirely

**Comment by DylanC** [comment]
@PolkinaAA - Paste as new image is designed to use the whole image. Do you think it should work for a selection?

**Comment by pollekepol** [comment]
No, with using the pointertool and then copy and paste as a new image give the same results: a copy of the original image

**Comment by DylanC** [comment]
@pollekepol - What are you expecting to happen when you "Paste as new image" in your example above? I just want to make sure I understand.

**Comment by pollekepol** [comment]
I selected half of the image, then paste the selection as a new image.
Now I did the same in PhotoFiltre and this is what I get and what i want :)
![knipsel](https://user-images.githubusercontent.com/46296721/50574248-c0cee580-0de4-11e9-8afe-0d310501c406.JPG)

**Comment by DylanC** [comment]
@pollekepol - Perfect, you and @PolkinaAA have the same issue then. I will work on a fix.

**Comment by DylanC** [comment]
@PolkinaAA @pollekepol - Fix pushed in latest commit.(245f7e3c03fa1b8dc22706faa3df29413d565182) This fix will arrive in v1.5.7.
