### ISSUE TITLE
 Preview mode "Hue Variation"

### ISSUE THREAD

**Issue by PolkinaAA** [PhotoFlare/photoflare#163]
Operating system: Windows 10 x64
Program version: PhotoFlare v1.5.5

Open program
Open image
Click on Hue Variation
In preview mode the rectangular image will square image

**Comment by DylanC** [comment]
@PolkinaAA - The preview is already a rectangle. Do you expect it to be wider?

**Comment by DylanC** [comment]
@PolkinaAA - Pushed in some updates to the Hue dialog. The change will be in the next release.
