### ISSUE TITLE
Fail Indexed Mode

### ISSUE THREAD

**Issue by PolkinaAA** [PhotoFlare/photoflare#166]
Operating system: Windows 10 x64
Program version: PhotoFlare v1.5.5

Open program
Open image
Click on Indexed Mode
The image will not change

**Comment by DylanC** [comment]
@PolkinaAA - It does for me. What are you expecting to happen?

**Comment by DylanC** [comment]
@PolkinaAA - The Indexed mode is a toggle for the actual mode. The image will not change unless you make edits. Then if indexed mode is enabled your image will return in indexed format instead of RGB format.
