### ISSUE TITLE
Setup Travis CI for build AppImage and deploy it to GitHub

### ISSUE THREAD

**Issue by Symbian9** [PhotoFlare/photoflare#167]
Compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

### TODO

1. https://github.com/appimage/appimagekit
1.1 https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/probonopd/uploadtool

**PLEASE NOTE:** For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) **prior to merging this**, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by DylanC** [comment]
@Symbian9 - Hi there, The app is building with Travis CI on every push currently:
https://travis-ci.org/PhotoFlare/photoflare/builds/

I did investigate AppImage before but I was unsure about the steps to take implementing it. I can look at this again if I have the time to research and implement it.

**Comment by Symbian9** [comment]
> I did investigate AppImage before but I was unsure about the steps to take implementing it.

If you need any help with `.travis.yml` script setup for AppImage — ask @probonopd, he really could help you! ;-)

Also, think, @aferrero2707 could help with AppImage as he already provide few builds for other FOSS apps

- https://github.com/aferrero2707/krita
  - https://github.com/aferrero2707/krita/blob/master/.travis.yml
- https://github.com/aferrero2707/RawTherapee
  - https://github.com/aferrero2707/RawTherapee/blob/master/.travis.yml
https://github.com/aferrero2707/PhotoFlow
  - https://github.com/aferrero2707/PhotoFlow/blob/master/.travis.yml
- https://github.com/aferrero2707/gimp-appimage
- https://github.com/aferrero2707/hugin-appimage
- https://github.com/aferrero2707/darktable

There are many other Qt apps, that already setup AppImage, listed on [AppImage Hub](https://appimage.github.io/apps/):

- https://github.com/jimevins/glabels-qt
  - https://github.com/jimevins/glabels-qt/blob/master/.travis.yml
https://github.com/tamlok/vnote
  - https://github.com/tamlok/vnote/blob/master/.travis.yml

**Comment by probonopd** [comment]
Can you get it to build on Ubuntu trusty without

https://github.com/PhotoFlare/photoflare/blob/abd431aee50e828bff2b2b54218a29f2b26d0d71/.travis.yml#L9

Then it should be easy.

This is needed because the resulting binaries will only run on newer, but not older, systems than the build systems. Hence one should always build on the oldest still-supported distribution.

**Comment by DylanC** [comment]
@probonopd - I could go back to using certain methods supported on 16.04. 
https://github.com/PhotoFlare/photoflare/commit/7ab9a6d13bfb9529227083205001013e277451d7

I switched to using newer Qt methods for improved performance. Would I need to wait until 16.04 is unsupported before using the new methods again?

**Comment by aferrero2707** [comment]
@DylanC @probonopd 
Sorry for joining the party a bit late...
I am currently providing AppImages for a couple of Qt-based projects, and in both cases I am using a CentOS7 docker container for this.

You can see an example of working configuration here: https://github.com/aferrero2707/hdrmerge-ci

Let me know if something is not clear in the logic of the building and packaging scripts...

**Comment by probonopd** [comment]
Since Ubuntu 14.04 is currently the oldest still-supported LTS release, it is recommended to use nothing newer than it.

**Comment by aferrero2707** [comment]
@probonopd @DylanC as far as I can tell, the AppImages that I am building on CentOS7 run fine on Ubuntu 14.04, but they are based on a Glibc version lower than what Ubuntu 14.04 provides (2.17 instead 2.19, if I am not wrong...).

However, CentOS7 provides packages for Qt 5.9.2, if that is recent enough for you...

**Comment by probonopd** [comment]
Recent versions of Qt are available for 14.04, e.g., https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.11.0-xenial

**Comment by Symbian9** [comment]
> Recent versions of Qt are available for 14.04, e.g., https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.11.0-xenial

You give link to Xenial (16.04)

Here is link for Trusty (14.04)

- https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.10.1-trusty

**Comment by DylanC** [comment]
@probonopd @Symbian9 - I tried to update the travis ci file to just build it on trusty, however it is having trouble finding the packages on the PPA:

`E: Unable to locate package qt511base`

**Comment by probonopd** [comment]
See the package names here: https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.10.1-trusty

It's `qt510base `.

**Comment by probonopd** [comment]
Started work at

https://github.com/probonopd/photoflare/blob/f3df3cb2430d7abbba50f2bfa1e32e93e13a5d77/.travis.yml

but getting a compile error:

```
src/managers/FilterManager.cpp: In member function ‘QImage FilterManager::fitImage(const QImage&)’:
src/managers/FilterManager.cpp:388:18: error: ‘class Magick::Image’ has no member named ‘thumbnail’
     magickImage->thumbnail(Magick::Geometry(640,400,0,0,false,false));
                  ^
src/managers/FilterManager.cpp: In member function ‘QImage FilterManager::cropToCenter(const QImage&)’:
src/managers/FilterManager.cpp:465:18: error: ‘class Magick::Image’ has no member named ‘extent’
     magickImage->extent(Magick::Geometry(640,400,0,0,false,false),Magick::Color(127,127,127),Magick::StaticGravity);
                  ^
src/managers/FilterManager.cpp: In member function ‘QPolygon FilterManager::selectArea(const QImage&, const QPoint&, int, bool)’:
src/managers/FilterManager.cpp:773:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int j=0; j<magickImage->rows(); j++)
                                      ^
src/managers/FilterManager.cpp:776:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i=0; i<magickImage->columns(); i++)
                                             ^
src/managers/FilterManager.cpp:783:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if((i == magickImage->columns() - 1) && marked)
                                               ^
src/managers/FilterManager.cpp:786:75: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
             if(magickImage->pixelColor(i,j) == Magick::ColorRGB (0, 0, 0) && !marked ||
                                                                           ^
src/managers/FilterManager.cpp:801:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if((i == magickImage->columns() - 1) && marked)
                                               ^
src/managers/FilterManager.cpp:804:74: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
             if(magickImage->pixelColor(i,j) == Magick::ColorRGB(0, 0, 0) && !marked ||
                                                                          ^
src/managers/FilterManager.cpp: In member function ‘QImage FilterManager::floodFillOpacity(const QImage&, const QColor&, int)’:
src/managers/FilterManager.cpp:829:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int j=0; j<magickImage->rows(); j++)
                                      ^
src/managers/FilterManager.cpp:831:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i=0; i<magickImage->columns(); i++)
                                             ^
src/managers/FilterManager.cpp: At global scope:
src/managers/FilterManager.cpp:593:28: warning: ‘MagickLib::ChannelType channelById(int)’ defined but not used [-Wunused-function]
 static Magick::ChannelType channelById(int channelId)
                            ^
make: *** [FilterManager.o] Error 1
make: *** Waiting for unfinished jobs....
```

https://travis-ci.org/probonopd/photoflare/builds/466290284#L886

**Comment by probonopd** [comment]
If worst comes to worst we need to compile https://travis-ci.org/ImageMagick/ImageMagick on our own.

**Comment by DylanC** [comment]
@probonopd - I would prefer not to downgrade Graphicsmagick as that would mean removing features from the latest released version. Do we have to go as far back as trusty or could we use xenial?

**Comment by probonopd** [comment]
Currently the oldest still-supported LTS release is trusty so we recommend that. I guess we can compile http://www.graphicsmagick.org there.
