### ISSUE TITLE
Eraser tool radius =0

### ISSUE THREAD

**Issue by YatkinMA** [PhotoFlare/photoflare#169]
Program version: PhotoFlare v1.5.5

Summary: Eraser tool radius =0.
Component: EraserTool.
Severity: Major.
Platform: Windows 7.
Steps to reproduce:
1.Start program.
2.Click "Eraser tool" button.
3. Set radius = 0
Result: Value 0.
Expected Result: Value more 0.
[Eraser tool.zip](https://github.com/PhotoFlare/photoflare/files/2616282/Blur.tool.zip)

**Comment by DylanC** [comment]
@YatkinMA - This is actually the Eraser tool. I have updated your issue description. Confirmed as a bug. (Zero radius should not be an option)

**Comment by DylanC** [comment]
@YatkinMA - It was only a display problem. It should have 1 as the default showing since 1 is the lowest value. Fix pushed in for the next release. Thanks.
