### ISSUE TITLE
Spray paint over part of the sheet

### ISSUE THREAD

**Issue by YatkinMA** [PhotoFlare/photoflare#171]
Program version: PhotoFlare v1.5.5

Summary: When using spray in the upper left corner appears shaded sector
Component: Spray can
Severity: Major.
Platform: Windows 7.
Steps to reproduce:
1.Start program.
2. Create a new sheet
3.Click "Spray can" button.
Result: When using spray in the left upper corner it is colored.
Expected Result: The spray can tool is selected without painting the sheet.
[Spray.zip](https://github.com/PhotoFlare/photoflare/files/2619992/Spray.zip)

**Comment by DylanC** [comment]
@YatkinMA - I've seen your video but this does not happen to me in v1.5.5 or v1.5.6. Do you have more information on how to produce this issue?

**Comment by YatkinMA** [comment]
System Windows 7 x64
Version 1.5.5
1. Create or open an image;
2. Choose any tool other than spray;
3. Choose a spray;

**Comment by DylanC** [comment]
Closing for now unless I can reproduce this behaviour. Could be related to Windows 7. Officially we support Windows 10.
