### ISSUE TITLE
FotoFlare Czech localization

### ISSUE THREAD

**Issue by pafri** [PhotoFlare/photoflare#176]
Hi,
please commit the attached translation of the app into Czech language (.zip archive).
Happy Christmas from Moravia

[fotoflare_cs.zip](https://github.com/PhotoFlare/photoflare/files/2705537/fotoflare_cs.zip)

**Comment by DylanC** [comment]
@pafri - This is great thank you! I will look at this soon enough. Hope you have a fantastic Christmas! :100:

**Comment by DylanC** [comment]
@pafri - I have this added now. Thanks again!
