### ISSUE TITLE
Text can't be edited

### ISSUE THREAD

**Issue by PolliRedHead** [PhotoFlare/photoflare#177]
Summary: Text can't be edited.
Component: TextTool.
Version: 1.5.6.1.
Severity: Major.
Platform: Windows 10 x64.
Steps to reproduce:
1. Start program.
2. Click "new" button.
3. Create an any image.
4. Add any text.
5. Deselected text.
6. Edit text.
Result: Text can't be edited.
Expected Result: Text edited.

**Comment by DylanC** [comment]
@PolliRedHead - This is working as intended currently. I don't think this will be changed until v2.0.

**Comment by DylanC** [comment]
Documentation page has been updated to include this information:
https://photoflare.io/documentation/adding-editing-text/

Thanks.
