### ISSUE TITLE
[CropTool] “Undo” button doesn’t work as expected

### ISSUE THREAD

**Issue by daschuk** [PhotoFlare/photoflare#179]
### Description
The “Undo” button doesn't work as expected when clicking on the button several times.

### Steps to reproduce
1.	Open a new file.
2.	Use “Crop” action.
3.	Repeat “Crop” action.
4.	Click on "Undo" twice.

### Actual result
The  “Undo” button works on the first time but doesn’t work on the second time (it works through once).

### Expected Result
The “Undo” button should cancel action after every click 

### Environment
Windows 10

![undo-1](https://user-images.githubusercontent.com/47143653/51907936-e0185d00-23fa-11e9-941c-fd34ca184139.gif)

**Comment by DylanC** [comment]
@daschuk - Confirmed. Just seems to happen with the Crop tool because I think making the selection counts as an Undo step even though the image has not changed.

**Comment by DylanC** [comment]
Put in a fix for the selection to not add an undo step.
