### ISSUE TITLE
The “Save” button is disabled after canceling changes

### ISSUE THREAD

**Issue by daschuk** [PhotoFlare/photoflare#180]
### Description
After canceling all changes in a file the “Save” button is disabled.

### Steps to reproduce

1.	Open a new file.
2.	Make some changes.
3.	Click on “Save”.
4.	Cancel changes.

### Actual result
The Save button is disabled.

### Expected Result
The Save button unable.

### Environment
Windows 10 x 64 bit

![save](https://user-images.githubusercontent.com/47143653/51909200-9b8ec080-23fe-11e9-9905-576dea21a93d.gif)

**Comment by DylanC** [comment]
@daschuk - If you undo all changes you will not have changes to be saved. This seems like correct behaviour to me.
