### ISSUE TITLE
Different title for the tool 

### ISSUE THREAD

**Issue by daschuk** [PhotoFlare/photoflare#182]
### Description

"Colour Dropper" is not the correct title. In  Documentation this tool called "Colour Picker".

### Steps to reproduce:
1.	Start the program;
2.	Move the mouse over the tool "Colour Dropper".

### Actual result:
The title of the tool is "Colour Dropper".

### Expected result:
The title of the tool should be "Colour Picker".

### Environment:
Windows 10 x 64 bit.

![incorrected](https://user-images.githubusercontent.com/47143653/51992822-4925d080-24e0-11e9-8e64-2b423f2bc5a7.gif)

**Comment by DylanC** [comment]
@daschuk - Pushed fix for this. Thanks.
