### ISSUE TITLE
Colour picker selecting colour from wrong pixel location

### ISSUE THREAD

**Issue by SpyroDr** [PhotoFlare/photoflare#183]
**Dropper works from the backside**

**Severity:** low
**Repeatability:** stable

**Steps to reproduce:**
1. Open application
2. Choose a brush
3. Paint the area
4. Select a dropper
5. Apply

**Expected Result:** The dropper captures color.
**Actual result:** not working properly.

**Environment:**
Windows 10 x 64 bit.
PhotoFlare v1.5.6.1

**Comment by DylanC** [comment]
@SpyroDr - This is working for me on Windows 10 64bit. Do you have a .gif recording?
