### ISSUE TITLE
Translation button not restarting app on Windows

### ISSUE THREAD

**Issue by SpyroDr** [PhotoFlare/photoflare#184]
**Translation in another language**

**Severity:** medium
**Repeatability:** stable

**Repetition steps:**
1.	Run the program
2.	Click on «Preferences»
3.	Click on «Startup»
4.	Choose language
5.	Click on apply to start

**Expected result:** We should interface program in another language.
**Fact result:** We see that program is closed.

**Environment:**
Windows 10 x 64 bit.
PhotoFlare v1.5.6.1

**Comment by DylanC** [comment]
@SpyroDr - This is working on Windows 10 64bit for me. What version of PhotoFlare is this?

**Comment by SpyroDr** [comment]
@DylanC PhotoFlare v1.5.6.1

**Comment by DylanC** [comment]
@SpyroDr - Pushed fix for this. Thanks.
