### ISSUE TITLE
Default values are only pixels

### ISSUE THREAD

**Issue by SpyroDr** [PhotoFlare/photoflare#185]
**Default values are only pixels**

**Severity:** medium
**Repeatability:** stable

**Steps to reproduce:**
1.	Run the program
2.	Click on «Preferences»
3.	Click on «Default values»
4.	Don’t choose units

**Expected result:** We should choose any units.
**Fact result:** We see that choice is restricted with 

**Environment:**
Windows 10 x 64 bit.
PhotoFlare v1.5.6.1

**Comment by DylanC** [comment]
Confirmed.

**Comment by DylanC** [comment]
@SpyroDr - This has just been fixed. (5f2036c4f605d3b35c5f54568271f5c9866bfdfc) You will find this fix in the next Community Edition release v1.5.7. Thanks.
