### ISSUE TITLE
«Automate/batch» don’t work

### ISSUE THREAD

**Issue by SpyroDr** [PhotoFlare/photoflare#188]
**«Automate/batch» don’t work**

**Severity:** high
**Repeatability:** stable

**Steps to reproduce:**
1. Run the program
2. Click on «tools» in text panel
3. Click on « Automate/batch»
4. Select items
5. Click on «ok»

**Expected result:** Save changed picture.
**Fact result:** Save empty white square.

**Environment:**
Windows 10 x 64 bit.
PhotoFlare v1.5.6.1

**Comment by DylanC** [comment]
Working in v1.5.5. Must investigate what has broken 1.5.6.1.

**Comment by DylanC** [comment]
@SpyroDr - Thanks for spotting this. I have pushed a fix in just now. The fix will be available in v1.5.7.
