### ISSUE TITLE
Scroll up/down with mouse wheel should increase/decrease zoom level

### ISSUE THREAD

**Issue by glaubersm** [PhotoFlare/photoflare#191]
At least on linux, when I scroll up/down using the mouse wheel, zoom level decreases/increases.
I think that the inverse (increase/decrease) does more sense and it's the behavior expected
by most users.

My system:
Arch Linux
KDE Plasma desktop environment
photoflare 1.5.7

**Comment by DylanC** [comment]
@glaubersm - I will try to collect more opinions on this. So far I have not heard any users who would like this to be changed. It is similar to PhotoFiltre which does please some users already. Perhaps we could put something in the preferences for this to please all users? Let me know your thoughts.

**Comment by glaubersm** [comment]
yes, an option in preferences seems a good solution to me.

**Comment by DylanC** [comment]
@glaubersm - I know its been a bit of delay but it took me a while to get another "office day" for the project. I've added a zoom direction to preferences with Default and Inverted as the choices:

![newZoomDirSetting](https://user-images.githubusercontent.com/4488048/60260577-cb6cc200-98d1-11e9-8406-45cb9c3c9550.png)

**Comment by glaubersm** [comment]
Thank you very much @DylanC.
