### ISSUE TITLE
“Gradient tool” direction circle has additional left click available

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#193]
**Description**
Secondary left mouse click at direction circle in gradient menu makes point disappear 

**Severity**: low
**Repeatability**: stable

**Steps to reproduce**
1.	Open new file
2.	Use “Gradient” feature from filterbar
3.	Click any position on direction circle
4.	Make secondary left mouse click at the same place
5.	Confirm with “OK” button

**Actual result**
Selected mark disappear but the tool retains its functionality

**Expected Result**
Usually gradient tool saves selected point in checked position, but if you make those point invisible and confirm changes, then for the next launch point returns to its original place, but it should stand still as other tools do after apply

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
Ubuntu 18.04.2 LTS x64
PhotoFlare 1.5.7
![2](https://user-images.githubusercontent.com/47425413/53858341-5b79b980-400c-11e9-9b10-90d3cf61c0cc.gif)

**Comment by DylanC** [comment]
@bmyagkov - Interesting bug. Thanks.

**Comment by DylanC** [comment]
@bmyagkov - Fix pushed. Thanks.
