### ISSUE TITLE
"Hue variation” requires confirm color twice

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#194]
**Description**
Select once is not enough to change the color of the selected box. User must confirm color twice before color of box changes.
	
**Severity**: low
**Repeatability**: stable

**Steps to reproduce**
1.	Open new file
2.	Use “Hue variation” feature from filterbar
3.	Click top left corner colored box and choose a color different from the default
4.	Repeat step 3

**Actual result**
It is required to click twice to makes box apply right color

**Expected Result**
Box should change its color from the first attempt

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
PhotoFlare 1.5.7
![3](https://user-images.githubusercontent.com/47425413/53858399-9bd93780-400c-11e9-8bdc-27100d739bbb.gif)

**Comment by DylanC** [comment]
@bmyagkov - Confirmed.

**Comment by DylanC** [comment]
@bmyagkov - This does not happen on Ubuntu, since it has a different colour picker.
![Screenshot from 2019-03-09 11-01-52](https://user-images.githubusercontent.com/4488048/54070684-d7694100-425a-11e9-8512-6096cd7901e9.png)

**Comment by bmyagkov** [comment]
> @bmyagkov - This does not happen on Ubuntu, since it has a different colour picker.
> ![Screenshot from 2019-03-09 11-01-52](https://user-images.githubusercontent.com/4488048/54070684-d7694100-425a-11e9-8512-6096cd7901e9.png)

@DylanC Indeed. Typo crept into my notes, I apologize for that
