### ISSUE TITLE
Clicking at settings track line does not commit changes

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#195]
**Description**
Click directly on track line at settings makes slider moves but do not apply changes done by that way 

**Severity**: medium
**Repeatability**: stable

**Steps to reproduce**
1.	Click “Preferences”
2.	Click “History”
3.	Click straight on track line left or right from slider
4.	Apply changes

**Actual result**
Turning settings slider done by that way makes no changes at history, compression and compression menu dialog too

**Expected Result**
There should be no difference at method used in move a slider to apply changes

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
Ubuntu 18.04.2 LTS x64
PhotoFlare 1.5.7
![4rev2](https://user-images.githubusercontent.com/47425413/53858463-e6f34a80-400c-11e9-9235-065429a0a40a.gif)

**Comment by DylanC** [comment]
@bmyagkov - Confirmed.

**Comment by DylanC** [comment]
@bmyagkov - I have pushed in a fix for this. It will be in the next release. Thanks!
