### ISSUE TITLE
Application reset settings to their defaults

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#196]
**Description**
Application settings returns to defaults after two following reloads 

**Severity**: medium
**Repeatability**: stable	

**Steps to reproduce**
1.	Start the program
2.	Open “Preferences”
3.	Tune any settings you want
4.	Confirm changes by clicking “OK” button
5.	Close and open application two times

**Actual result**
Application forces you to enter the preferences every third time because the settings are reset to their defaults regularly

**Expected Result**
The settings should remain as they were once set by the user 

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
PhotoFlare 1.5.7
![5](https://user-images.githubusercontent.com/47425413/53858527-26ba3200-400d-11e9-9b44-85ccdcac6120.gif)

**Comment by DylanC** [comment]
@bmyagkov - This doesn't happen for me on Ubuntu. I will have a look at Windows. Is this installed or portable version?

**Comment by DylanC** [comment]
@bmyagkov - Confirmed on Windows. (installed version)
