### ISSUE TITLE
“Transparent color” has different titles

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#198]
**Description**
Menu bar called “Transparent color” while the button popup tip shows “Transparent colour” 

**Severity**: low
**Repeatability**: stable	

**Steps to reproduce**
1.	Open new file
2.	Move the mouse over the tool “Transparent coloUr”
3.	Click on selected tool

**Actual result**
The tool titles are different from each other

**Expected Result**
Tools menu names must have the same signature 

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
Ubuntu 18.04.2 LTS x64
PhotoFlare 1.5.7
![7](https://user-images.githubusercontent.com/47425413/53858626-87496f00-400d-11e9-92e1-7ee9ec892d74.png)

**Comment by DylanC** [comment]
@bmyagkov - Confirmed.

**Comment by DylanC** [comment]
Pushed fix for this. Thanks.
