### ISSUE TITLE
Canceling “Image Size” dialog displays incorrect image status value

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#199]
**Description**

Opening “Resize image” to specify the current image size, reports a false value at the status menu bar after closing window by clicking “Cancel” button

 **Severity**: low
**Repeatability**: stable	

**Steps to reproduce**
1.	Open new file
2.	Open “Image size” from top menu
3.	Click on “Cancel” button

**Actual result**
Status bar returns (-1 x 1) value after closing “Resize image”

**Expected Result**
Should display the correct image size
 
**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
Ubuntu 18.04.2 LTS x64
PhotoFlare 1.5.7
![9](https://user-images.githubusercontent.com/47425413/53858724-d5f70900-400d-11e9-8350-85720fe24cd2.gif)

**Comment by DylanC** [comment]
@bmyagkov - Confirmed.

**Comment by DylanC** [comment]
@bmyagkov - Fixed. Thanks.
