### ISSUE TITLE
“Show grid” marked as applied even if not used

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#200]
**Description**
Opening “Show grid” with following “Cancel” click marks menu button with “check” same as applied action 

**Severity**: low
**Repeatability**: stable	

**Steps to reproduce**
1.	Open new file
2.	Open “Show grid” from “View” in top menu
3.	Click on “Cancel” button
4.	Click on “View” in top menu

**Actual result**
A button informs you like the effect was applied while the action was canceled.

**Expected Result**
The button must remain unchecked if the tool has not been used.

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
Linux 18.04.2 LTS x64
PhotoFlare 1.5.7
![10](https://user-images.githubusercontent.com/47425413/53858780-fc1ca900-400d-11e9-8031-65f9f5219a39.gif)

**Comment by DylanC** [comment]
@bmyagkov - Confirmed.

**Comment by DylanC** [comment]
@bmyagkov - Fixed. Thanks.
