### ISSUE TITLE
“Transparent color” allowed to be open multiple times

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#201]
**Description**
“Transparent color” menu is allows to be open multiply times, it’s also can be run simultaneously with other menu gumps and could be keep open as separate application even when PhotoFlare is already closed

**Severity**: high
**Repeatability**: stable	

**Steps to reproduce**
1.	Open new file
2.	Click on “Transparent color” as much times as you want to
3.	Close the main window of PhotoFlare with right click from task bar

**Actual result**
“Transparent color” would be running as long as you want to. The all menu items will continue to function. PhotoFlare.exe keeps floats in memory. 

**Expected Result**
“Transparent color” as well as all other menu tools should be launched in agreement with the application and should be eliminated together with the program.  

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
Ubuntu 18.04.2 LTS x64
PhotoFlare 1.5.7
![12](https://user-images.githubusercontent.com/47425413/53858850-3ede8100-400e-11e9-880f-2a78ee843357.gif)

**Comment by DylanC** [comment]
@bmyagkov - You are very good at finding bugs. Confirmed. 👍

**Comment by bmyagkov** [comment]
> @bmyagkov - You are very good at finding bugs. Confirmed. 👍

Thanks, much appreciated.

**Comment by DylanC** [comment]
@bmyagkov - Fixed this and all dialogs. Thanks.
