### ISSUE TITLE
Language restart button not working 

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#202]
**Description**
Changing language immediately closes application without saving changes and return crash messages after

**Severity**: high
**Repeatability**: stable	

**Steps to reproduce**
1.	Start the program
2.	Open new file
3.	Do any changes with file
4.	Open “Preferences”
5.	Open “Startup” section
6.	Select any language you want
7.	Press “Restart to apply” button

**Actual result**
Application immediately closes without saving changes that user has been already done with the file and then lend crash message after

**Expected Result**
The application should check for any changes made to the file and offer to save them before applying the new language settings.

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
Ubuntu 18.04.2 LTS x64
PhotoFlare 1.5.7
![13](https://user-images.githubusercontent.com/47425413/53858910-81a05900-400e-11e9-9477-62f18b24b9ce.gif)

**Comment by DylanC** [comment]
Dup of #184

**Comment by DylanC** [comment]
@bmyagkov - Pushed fix for this. Thanks.
