### ISSUE TITLE
“Resize Image” incorrectly calculates the aspect ratio

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#203]
**Description**
The tool incorrectly calculates aspect ratio even with the “preserve aspect ratio” button checked and as a result the image loses its original proportions

**Severity**: high
**Repeatability**: stable	

**Steps to reproduce**
1.	Start the program
2.	Create new image with 1024 height and 768 width
3.	Open “Image Size” from top menu
4.	Make sure “Preserve aspect ratio” checked
5.	Change width to 500, height will automatically set to 400 
6.	Press “OK” to confirm

**Actual result**
Image will resizes to 500x400 from 1024x768 as promised in the resize window

**Expected Result**
The correct value should be 500x375 which will preserve the correct aspect ratio and will not distort the original image 

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
Ubuntu 18.04.2 LTS x64
PhotoFlare 1.5.7
![14](https://user-images.githubusercontent.com/47425413/53858983-c7f5b800-400e-11e9-822d-6f707f256d1f.gif)

**Comment by DylanC** [comment]
@bmyagkov - Previously I put in a fix for Resize image but that upset behaviour for new images. Now we have a problem with Resize again after putting in fix for new images. 😐

**Comment by DylanC** [comment]
@bmyagkov - I have a fix pushed in for this now. Initial testing shows good results and fixes your issue.

**Comment by DylanC** [comment]
@bmyagkov - Its possible to check this via the AppImage on Linux if you want.
https://github.com/PhotoFlare/photoflare/releases/tag/continuous

Fix will be in the next release. (very soon)
