### ISSUE TITLE
“Automate/Batch” allows program to crash

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#204]
**Description**
The application allows you to set the dimensions value at 0 for height and width in the image resize section, which is makes program to crash immediately after confirm changes

**Severity**: high
**Repeatability**: stable	

**Steps to reproduce**
1.	Start the program
2.	Chose “Automate/Batch” from tools at top menu
3.	Click “Add files” and select any image
4.	Switch to “Image size” section
5.	Check “Image Size” box first
6.	Check “Preserve Aspect Ratio”
7.	Enter any value for height or width, the application will return 0
8.	Press “OK” button

**Actual result**
Program closes and land crash message immediately

**Expected Result**
The application must check the value before allowing changes to be confirmed.

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
Ubuntu 18.04.2 LTS x64
PhotoFlare 1.5.7
![1](https://user-images.githubusercontent.com/47425413/53869133-2a0fe680-402a-11e9-9452-6ad706de8f5e.gif)

**Comment by DylanC** [comment]
@bmyagkov - Confirmed.

**Comment by DylanC** [comment]
@bmyagkov - Fixed, thanks.
