### ISSUE TITLE
copy without selection copies nothing

### ISSUE THREAD

**Issue by pdbogen** [PhotoFlare/photoflare#205]
hullo!

as a result of, I believe, 245f7e3c03fa1b8dc22706faa3df29413d565182, the behavior of Copy when nothing is selected (e.g., on initial opening of an image; or after clearing a selection with a single click) is to copy an empty image.

I guess `widget->selection().isEmpty()` is unexpectedly returning `false` in these circumstances.

This is true in community 1.5.7 and 1.5.8, at least.

**Comment by DylanC** [comment]
@pdbogen - Oh dear. Fixed one bug and another caused. I will look into this, confirmed on v1.5.8.

**Comment by DylanC** [comment]
@pdbogen - Pushed fix for this. https://github.com/PhotoFlare/photoflare/commit/d33ec288e787c7e878a87ea5d3da4b29328b79e6

**Comment by DylanC** [comment]
@pdbogen - If you are on Ubuntu can you try this installer for me?
https://launchpad.net/photofiltre-lx/trunk/v1.5.8.1/+download/PhotoFlare_CE_1.5.8.1_amd64_18.04.deb

**Comment by pdbogen** [comment]
Thanks! I will when I get a chance. I'm off doing non-computer things for a bit, so it might not be until Monday.

**Comment by DylanC** [comment]
@pdbogen - No problem. Monday suits me fine!

**Comment by pdbogen** [comment]
got it! this is working well for me. I'll go ahead and close this issue.

fyi I use photoflare as a tool to crop/annotate screenshots, with a script like this:
```sh
#!/bin/sh

set -e

sleep .2s
ss="$(mktemp /tmp/XXXXXX.png)"
if [ "$1" = "--full" ]; then
  DISPLAY=:0 gnome-screenshot --display=:0 -f "$ss"
else
  DISPLAY=:0 gnome-screenshot --display=:0 -a -f "$ss"
fi
photoflare "$ss" &
```

If that's a workflow that piques you're interested, there are two features that come to mind that would be nice to have- a tool to draw boxes and a tool to "redact" (which might be solid boxes in the simplest case, but a very chunky pixellation effect is visualyl nice).

It would also be convenient for me to be able to specify tool settings via the command line, e.g., so that when the window opens, paintbrush @ 5px red is pre-selected.

If these features sound worthwhile to you, I could open seperate issues to track each one?

**Comment by DylanC** [comment]
@pdbogen - Great to hear its working! It was working for me but I needed you to confirm. This workflow is quite interesting. 

I may already have something open for the drawing of boxes.
https://github.com/PhotoFlare/photoflare/issues/59

However, open both issues and I can always mark one of them as a duplicate. The extra information on your requirements in the issue will be useful. Do open an issue for the command line feature too!
