### ISSUE TITLE
Can’t draw in ‘Indexed Mode”

### ISSUE THREAD

**Issue by kerenberry** [PhotoFlare/photoflare#206]
Operating system: Windows 10 x64
Program version: PhotoFlare v1.5.8

Description
Undo action after switching “Indexed Mode” makes ripples on image and does not allow to draw.

Steps to reproduce:
1. Start the program
2. Open an image
3. Switch to “Indexed Mode”
4. Draw anything
5. Undo Draw
6. Try to draw anything

![IndexedMode](https://user-images.githubusercontent.com/27842460/56721605-71376f80-676f-11e9-83a1-7a56c3dffb8e.gif)

**Comment by DylanC** [comment]
@kerenberry - Confirmed on v1.5.8.1.

**Comment by DylanC** [comment]
Fixed in v1.6.6.
