### ISSUE TITLE
Default width values of a new file are different sometimes

### ISSUE THREAD

**Issue by kerenberry** [PhotoFlare/photoflare#208]
Operating system: Windows 10 x64 
Program version: PhotoFlare v1.5.8 

Description
Width value of “New” file changes after some opening and closing of program. Sometimes opening “New” window by clicking in Menu “File” and opening “New” window by clicking on its icon also gives different values of width

![Width1](https://user-images.githubusercontent.com/27842460/56723229-bf01a700-6772-11e9-82a8-443e8ab5d68d.gif)

![Width2](https://user-images.githubusercontent.com/27842460/56723919-21a77280-6774-11e9-9ae2-8a502099ed17.gif)

**Comment by DylanC** [comment]
@kerenberry - Hmm.. this one isn't happening for me on Ubuntu or Windows 10 x64.

**Comment by DylanC** [comment]
Leaving this open a while longer in case someone else can reproduce.
