### ISSUE TITLE
Free resizing of some windows

### ISSUE THREAD

**Issue by kerenberry** [PhotoFlare/photoflare#209]
Operating system: Windows 10 x64 
Program version: PhotoFlare v1.5.8

Description
Free resizing of windows “Image Size”, “Canvas Size”, “Outside drop shadow” and  “New” minimize windows size

1) Start the program
2) Open any file
3) Click “Image” - “Image Size”
4) Resize window
5) Click “Image” - “Canvas Size”
6) Resize window
7) Click “Image” - “Outside drop shadow”
8) Resize window
9) Click “File” - “New”
10) Resize window

![Resize](https://user-images.githubusercontent.com/27842460/56724474-48b27400-6775-11e9-8cc8-0e3b71bdf80a.gif)

**Comment by DylanC** [comment]
@kerenberry - Confirmed on all operating systems.

**Comment by DylanC** [comment]
@kerenberry - Pushed fix for this. It will be released in v1.5.9. Thanks.
