### ISSUE TITLE
Release for Linuxmint 18.3

### ISSUE THREAD

**Issue by orion777** [PhotoFlare/photoflare#213]
Hello
Please can you provide an updated photoflare release for Linuxmint 18.3?

Thanks you so much

**Comment by DylanC** [comment]
@orion777 - v1.5.9 will be out soon. I can provide a build for 18.3 for this release.

**Comment by orion777** [comment]
Thanks you very much let me know when you release it.
Regards

**Comment by DylanC** [comment]
@orion777 - Do you want a .deb in particular or would you be happy to try the AppImage? https://github.com/PhotoFlare/photoflare/releases/tag/v1.5.9

**Comment by orion777** [comment]
Hello
Can you make a .deb for linuxmint 18.3 ?
Didi you fix the problem concerning the toolpalette with different size screen resolution ?
Thanks you very much
Regards

**Comment by DylanC** [comment]
@orion777 - I'm not sure regarding the toolpalette with small resolution. I don't have equipment with small resolution to test. I tried to build Photoflare on Mint 18 tonight and I had issues. 

For now can you try to use the AppImage? It does work on Mint 18 or you can use our PPA but this supports Ubuntu 18.04/Mint 19 as a minimum.
