### ISSUE TITLE
The percentage of compression does not correspond to the actual while saving

### ISSUE THREAD

**Issue by Daniil212504** [PhotoFlare/photoflare#214]
Summary: The percentage of compression does not correspond to the actual while saving.

Component: Interface.

Severity: Trivial.

Platform: Windows 10.

Program version: 1.5.8.1 Community Edition.

Steps to reproduce:
    1. Start the program;
    2. Open an image;
    3. File -> Save As… -> Type File: jpg -> Save;
    4. Try to change the compression by clicking.

Result: Compression percentage is different from actual.

Expected result: Compression percentage is similar to actual.

Attachment: [compression.zip](https://github.com/PhotoFlare/photoflare/files/3178912/compression.zip)

**Comment by DylanC** [comment]
@Daniil212504 - I see. I think this needs the same fix as here (954d3de85b24abb713fb8c5e5ce79acac42835d3) Thanks!

**Comment by DylanC** [comment]
@Daniil212504 - Pushed a fix for this. Thanks.
