### ISSUE TITLE
Tif type image does not open

### ISSUE THREAD

**Issue by Daniil212504** [PhotoFlare/photoflare#216]
Summary: Tif type image does not open.

Severity: Major.

Platform: Windows 10.

Program version: 1.5.8.1 Community Edition.

Steps to reproduce:
1. Start the program;
2. File -> Open…;
3. Open tif type image.

Result: The image does not open.

Expected result: The image open.

Attachment: [tif type.zip](https://github.com/PhotoFlare/photoflare/files/3178971/tif.type.zip)

**Comment by DylanC** [comment]
Fixed via: https://github.com/PhotoFlare/photoflare/commit/742866dc6ad11c153f0e574c8af6f5e7f4b3b8da
