### ISSUE TITLE
Undo operation does not work after pasting copied item

### ISSUE THREAD

**Issue by Daniil212504** [PhotoFlare/photoflare#217]
Summary: Undo operation does not work after pasting copied item.

Component: Adjustments.

Severity: Major.

Platform: Windows 10.

Program version: 1.5.8.1 Community Edition.

Steps to reproduce:
1. Start the program;
2. Open an image;
3. Select the area with the pointer tool;
4. Copy selected area;
5. Paste copied area;
6. Try to return to the previous step of editing.

Result: Undo operation does not work, it is impossible to return to the previous step.

Expected result: Operation undo works, back to the previous step.

Attachment: [undo operation.zip](https://github.com/PhotoFlare/photoflare/files/3178992/undo.operation.zip)

**Comment by DylanC** [comment]
@Daniil212504 - Confirmed.

**Comment by DylanC** [comment]
@Daniil212504 - Fixed. Thanks.
