### ISSUE TITLE
No possibility to edit the text or move

### ISSUE THREAD

**Issue by nasynova** [PhotoFlare/photoflare#222]
1.	Start the program.
2.	Open the image.
3.	Image -> Text.
4.	Write any text.
5.	Select any area on the picture.
The result: no possibility to edit the text or move.
Expected result: it is possible to edit the text or move.
Video in attachment.
Reproduced: Windows 10.
Version of the program: 1.5.8.1.
Additional information: to cancel the operation select Undo.
Attachment: [No possibility to edit the text or move.zip](https://github.com/PhotoFlare/photoflare/files/3190122/No.possibility.to.edit.the.text.or.move.zip)

**Comment by DylanC** [comment]
@nasynova - If you click ok on the text dialog. The text can be moved around and edited if you click on it. If you clicked directly on the image the text has been "anchored", so you cannot edit any longer. Either this functionality could be enhanced or we could improve this to make it more user friendly by using more cursor icons and highlighting of your text object on screen.
