### ISSUE TITLE
File type “.tif” doesn’t open

### ISSUE THREAD

**Issue by nasynova** [PhotoFlare/photoflare#223]
1.	Start the program.
2.	Open the image.
3.	File -> Open.
4.	Select button “All Files -> TIFF (*.tif *.tiff)”
5.	Select file.tif and click a button “Open”.
6.	A message appears in the dialog box “Do you want to update this extension”.
7.	Select button “Save”.
The result: file type “.tif” doesn’t open.
Expected result: file type “.tif” opens.
Video in attachment.
Reproduced: Windows 10.
Version of the program: 1.5.8.1.
Attachment: [File type “.tif” doesn’t open.zip](https://github.com/PhotoFlare/photoflare/files/3190125/File.type.tif.doesn.t.open.zip)

**Comment by DylanC** [comment]
Dup of #216

**Comment by DylanC** [comment]
@nasynova - Fixed via 742866d
