### ISSUE TITLE
Cannot undo copied area

### ISSUE THREAD

**Issue by nasynova** [PhotoFlare/photoflare#224]
1.	Start the program.
2.	Open the image.
3.	File -> Open.
4.	Choose any area.
5.	To copy.
6.	Undo.
The result: cannot undo copied area.
Expected result: can undo copied area.
Video in attachment.
Reproduced: Windows 10.
Version of the program: 1.5.8.1.
Attachment: [Cannot undo copied area.zip](https://github.com/PhotoFlare/photoflare/files/3190128/Cannot.undo.copied.area.zip)

**Comment by DylanC** [comment]
@nasynova - Already fixed in the source last night. d74007aaecec1f614cc2f921dbf5bca082ae1c00 👍
