### ISSUE TITLE
Button “Undo” inactive

### ISSUE THREAD

**Issue by nasynova** [PhotoFlare/photoflare#225]
1.	Start the program.
2.	Open the image.
3.	View -> Show Grid.
4.	Set grid size 2.
5.	To press on right mouse button «Undo» or select the combination on the keyboard “Ctrl+Z”.
The result: button “Undo” inactive.
Expected result: button “Undo” active.
Video in attachment.
Reproduced: Windows 10.
Version of the program: 1.5.8.1.
Additional information: for undo the operation select again View -> Show Grid.
Attachment: [Button “Undo” inactive.zip](https://github.com/PhotoFlare/photoflare/files/3190130/Button.Undo.inactive.zip)

**Comment by DylanC** [comment]
@nasynova - Show grid does not modify the image. There is nothing to undo in this situation. The grid is to help the user align images. (grid snapping will be introduced at a later date)
