### ISSUE TITLE
Unnecessary duplicating Width and Height in the creating new file modal window

### ISSUE THREAD

**Issue by Cainthegall117** [PhotoFlare/photoflare#226]
![image](https://user-images.githubusercontent.com/50706520/57963330-da646a00-794c-11e9-8332-7cea833e2c84.png)
This fields are already shown in this window, no need to show them twice

**Comment by DylanC** [comment]
@Cainthegall117 - If you are changing the size of the image in cm/inches you will be able to see the preview of the image size in pixels on top. This design is on purpose.
