### ISSUE TITLE
Unnecessary control arrows near the Memory-field in the creating new file window  

### ISSUE THREAD

**Issue by Cainthegall117** [PhotoFlare/photoflare#227]
![image](https://user-images.githubusercontent.com/50706520/57963411-08967980-794e-11e9-9cc1-3545e45190f9.png)
This arrows shouldn't have any effect anyway, because memory depends on the size and resolution parameters, so they're should be removed

**Comment by DylanC** [comment]
@Cainthegall117 - I have the arrows removed now. Thanks.
