### ISSUE TITLE
Automatize/Batch feature. Field rigth from the filters list doesn’t show expected result of filters working. Also, Summary doesn’t show used filters. 

### ISSUE THREAD

**Issue by Cainthegall117** [PhotoFlare/photoflare#229]
![Capture4](https://user-images.githubusercontent.com/50706520/57963622-2f09e400-7951-11e9-8d94-adf3acae17c1.PNG)
![Capture5](https://user-images.githubusercontent.com/50706520/57963623-2f09e400-7951-11e9-81cf-ff57a578d31f.PNG)

**Comment by DylanC** [comment]
@Cainthegall117 - It looks like you didn't select any filters. Did you double click on any of them on the left side list?

**Comment by Cainthegall117** [comment]
@DylanC , oh, sorry, i thought it supposed to be added with one click. Yes, on this point there is no bug at all

**Comment by DylanC** [comment]
@Cainthegall117 - Hmm.. I think maybe it could be made to be more user friendly. I could add buttons in the middle to move filters left and right too.

**Comment by DylanC** [comment]
I've opened #237 for this. Thanks.
