### ISSUE TITLE
Zoom in  function works incorrectly

### ISSUE THREAD

**Issue by Cainthegall117** [PhotoFlare/photoflare#231]
Open a file and push Zoom in - picture will become smaller however it supposed to do the opposite
![gif1](https://user-images.githubusercontent.com/50706520/57963721-c15eb780-7952-11e9-9fc0-88a91f2281ad.gif)

**Comment by DylanC** [comment]
@Cainthegall117 - Yeah, there is something strange going on with it. I will look into it.

**Comment by DylanC** [comment]
@Cainthegall117 - I think what is happening is the zoom is going from autozoom mode to zoom by combo index. The index is 0 at the beginning so it goes to the first combo item (10%).

I think I need to compare the scale value from auto zoom to the combo items and find the next increment to use.

**Comment by DylanC** [comment]
@Cainthegall117  - I've added a feature to transition from auto scale to index scale. This will be in the next release v1.5.9. Hopefully I can implement something similar for zoom out too.
