### ISSUE TITLE
Instrument atributes are placed too high

### ISSUE THREAD

**Issue by Cainthegall117** [PhotoFlare/photoflare#234]
![image](https://user-images.githubusercontent.com/50706520/57964805-a5b0dc80-7965-11e9-9d62-5412b0164e8b.png)
![image](https://user-images.githubusercontent.com/50706520/57964811-ae091780-7965-11e9-9ed4-73197d6cf942.png)
![image](https://user-images.githubusercontent.com/50706520/57964817-bc573380-7965-11e9-8954-7664d8c42644.png)
![image](https://user-images.githubusercontent.com/50706520/57964824-c8db8c00-7965-11e9-9548-9b6cbc469f3e.png)

**Comment by DylanC** [comment]
@Cainthegall117 - I made an attempt to sort this. Let me know if you have any more issues.

**Comment by DylanC** [comment]
@Cainthegall117 - Looks Okay to me in v1.5.9. (Windows 10)
