### ISSUE TITLE
Picking Screen Color feature doesn't disable a screen until operation is done

### ISSUE THREAD

**Issue by Cainthegall117** [PhotoFlare/photoflare#235]
![gif1](https://user-images.githubusercontent.com/50706520/57964977-e7428700-7967-11e9-9b8e-927020380470.gif)
Select color, pick up screen color. Select some icon from the panel. Color will be picked after left click, but icon also will be activated

**Comment by DylanC** [comment]
@Cainthegall117 - I think you may be misunderstanding this feature. Its simply to pick a color to paint with. Not to pick a screen colour.
