### ISSUE TITLE
Panel moving works incorrectly

### ISSUE THREAD

**Issue by Cainthegall117** [PhotoFlare/photoflare#236]
Grab the gray instrument panel, then move it to the other panel. Other panel gonna be blocked. You can't just put panel back after moving it
![gif1](https://user-images.githubusercontent.com/50706520/57965569-1f4dc800-7970-11e9-937d-f75506a895de.gif)

**Comment by DylanC** [comment]
@Cainthegall117 - This does work. You need to move it more towards the bottom corner.
