### ISSUE TITLE
Flatpak installer needed

### ISSUE THREAD

**Issue by DylanC** [PhotoFlare/photoflare#238]
Tracking progress of the flatpak build here. Will need to follow steps here:
https://docs.flatpak.org/en/latest/first-build.html

**Comment by DylanC** [comment]
Followed environment setup via this page:
https://community.kde.org/Guidelines_and_HOWTOs/Flatpak

Added initial file here:
https://github.com/PhotoFlare/photoflare/commit/dac66b90f0dfda46a65c255b7dc27c9f211c01f1

Hit error when I ran it:
`Downloading sources
Initialised empty Git repository in /home/dylan/Desktop/.flatpak-builder/git/_home_dylan_Desktop_https_github.com_PhotoFlare_photoflare.git-V8DH4Z/
fatal: '/home/dylan/Desktop/https:/github.com/PhotoFlare/photoflare.git' does not appear to be a git repository
fatal: Could not read from remote repository.
`

**Comment by eszlari** [comment]
@DylanC Are you still interested in this? I could open PR on Flathub (https://github.com/flathub/flathub/pulls) with a working build manifest and then they will give you commit access to the repo.

**Comment by DylanC** [comment]
@eszlari - Yes, I would be interested. I will need to look at this again and see can I get the manifest to build successfully. I'm short on time to look at this currently but hopefully over the Christmas period I can try this again.

**Comment by hfiguiere** [comment]
Now that I have a submission almost ready (see flathub PR), would anyone upstream be interested to help maintaining it?

It is mostly a matter of updating on new releases.

**Comment by DylanC** [comment]
@hfiguiere - Many thanks for your help on this! I can help maintain going forward.
