### ISSUE TITLE
Ubuntu/Debian Store inclusion

### ISSUE THREAD

**Issue by DylanC** [PhotoFlare/photoflare#24]
Need to get into the Store to get much more users and visibility of the project.  

Already submitted to Getdeb.net:
https://bugs.launchpad.net/getdeb.net/+bug/1632672

Submitted to Ubuntu here:
https://bugs.launchpad.net/ubuntu/+bug/1711644

**Comment by sobujbd** [comment]
> Need to get into the Store to get much more users and visibility of the project.

Where visibility need to be increases?

**Comment by DylanC** [comment]
@sobujbd - I'm just saying that more users need to know about it. :)

**Comment by sobujbd** [comment]
Bye the way,
PhotoFlare now available on AlternativeTo.
[PhotoFlare Alternatives and Similar Software - AlternativeTo.net](https://alternativeto.net/software/photoflare/)

Also submitted on Slant (Best software comparison site) - Choose the best.
[PhotoFlare - What is the best photo editing software? - Slant](https://www.slant.co/topics/1188/viewpoints/24/~photo-editing-software~photoflare) _(Need to add Pros and Cons here)_

**Comment by DylanC** [comment]
@sobujbd - Thanks.

**Comment by DylanC** [comment]
As the first step for getting into Debian we have the following PPA created:
https://launchpad.net/~photoflare/+archive/ubuntu/ppa

Also the project now has an AppStream file (https://wiki.debian.org/AppStream) to help packaging for other distros:
https://github.com/PhotoFlare/photoflare/blob/master/appdata.xml

**Comment by DylanC** [comment]
We have both a maintainer and sponsor now. Package has been uploaded to the archive:
https://ftp-master.debian.org/new/photoflare_1.5.4-1.html

**Comment by DylanC** [comment]
PhotoFlare will soon be available in Ubuntu 19.04 and Debian:
https://launchpad.net/ubuntu/+source/photoflare

I hope to get a newer release of package in before the deadline.

**Comment by DylanC** [comment]
Photoflare is now available in Disco - https://packages.ubuntu.com/disco/photoflare
