### ISSUE TITLE
Missing license notices

### ISSUE THREAD

**Issue by donaldr3** [PhotoFlare/photoflare#242]
It seems that the project is lacking proper license notices. License notices at the top of source files let users know whether they may use the work under the current license or any later version. You can learn how to use GNU licenses at https://www.gnu.org/licenses/gpl-howto.en.html.

**Comment by DylanC** [comment]
@donaldr3 - Thanks. I will get this in there before our next release.

**Comment by DylanC** [comment]
@donaldr3 - Fixed this tonight. Let me know if I missed anything. :+1:
