### ISSUE TITLE
Switching language to german results in dutch!

### ISSUE THREAD

**Issue by stguenth** [PhotoFlare/photoflare#250]
I installed photoflare stable 1.62 64bit with ppa on ubuntu 18.04.

"Tools-Preferences-Startup":
When switching the language to german, after restart gui is not in german but in dutch.
![photoflare](https://user-images.githubusercontent.com/16766391/73606442-8d8ff480-45aa-11ea-8832-16132fdf5a05.png)

**Comment by DylanC** [comment]
@stguenth - Thank you for the bug report. The PPA still contains v1.6.1 from what I can see. I will investigate to see if this issue exists in the latest version.

**Comment by stguenth** [comment]
Ok, you are half right:

photoflare/bionic,now 1.6.1-0+766~ubuntu18.04.1 amd64  [installiert]
But:
![phtoflare-about](https://user-images.githubusercontent.com/16766391/73685679-dd63de00-46c6-11ea-8b9b-66ba53685603.png)

**Comment by DylanC** [comment]
@stguenth - Okay. The version number is incorrect in the PPA but I think v1.6.2 is actually the version released.

Code release date - 26th Jan.
Package build date - 27th Jan.

I'll have a look at this issue soon.

**Comment by DylanC** [comment]
@stguenth - It seems the contributor who submitted that wasn't very German but from a Dutch background. I'll make sure we have a more German translation in the next release. https://github.com/PhotoFlare/photoflare/commit/64510f1352c0def7829bc5b164177c2ee668fa7c 
Feel free to help!
http://photoflare.io/contributing/translations/

**Comment by DylanC** [comment]
@stguenth - de translation file has been updated. Look over this file and let me know if anything looks incorrect. https://github.com/PhotoFlare/photoflare/blob/master/languages/de.ts

**Comment by DylanC** [comment]
This change will be included in the upcoming v1.6.2.1 release.
