### ISSUE TITLE
Desktop naming mismatch

### ISSUE THREAD

**Issue by City-busz** [PhotoFlare/photoflare#263]
The desktop file name specified in [io.photoflare.photoflare.appdata.xml](https://github.com/PhotoFlare/photoflare/blob/master/io.photoflare.photoflare.appdata.xml#L24) is `io.photoflare.photoflare.desktop`, but the desktop file is named as [`photoflare.desktop`](https://github.com/PhotoFlare/photoflare/blob/master/installers/deb/DEBIAN/usr/share/applications/photoflare.desktop).

Please either rename the desktop file to `io.photoflare.photoflare.desktop`, or modify the metainfo file to match with the actual desktop file name.

**Comment by DylanC** [comment]
@City-busz - Does this fix your issue? 184ef11f4cc9245d4d2179ea26a514fcc9010d84

**Comment by City-busz** [comment]
Yes, it's okay now.
