### ISSUE TITLE
Windows Portable Link on photoflare.io needs updating

### ISSUE THREAD

**Issue by Lonke** [PhotoFlare/photoflare#264]
The download link for 'PhotoFlare 1.6.5 portable' under the Windows accordion returns a 404 error. I suspect this is due to version mismatch within the URL.

If the URL is changed to
https://launchpad.net/photofiltre-lx/trunk/v1.6.5/+download/Photoflare_CE_1.6.5_amd64_win_portable.zip
the file will download as expected.

![image](https://user-images.githubusercontent.com/8409189/85929412-cfe90380-b8b4-11ea-9c8b-06c2dac7bd0e.png)

**Comment by DylanC** [comment]
@Lonke - Fixed. Thanks.
