### ISSUE TITLE
Automatic/Batch - Image rotation incorrect

### ISSUE THREAD

**Issue by pollekepol** [PhotoFlare/photoflare#266]
**Wrong position**
When automatic/batch images and the size given is 2000 x 1500 pixels the images will be saved vertical and not horizontal.
Afterwards all the images must be rotated.

**Desktop
![screenshot](https://user-images.githubusercontent.com/46296721/90400324-96ef3300-e09c-11ea-8593-39ed16ca5264.png)
**
 - OS: Xubuntu 20.4

**Comment by DylanC** [comment]
@pollekepol - Thanks. I'll have a look at this when I get the chance.
