### ISSUE TITLE
Paint rectangles

### ISSUE THREAD

**Issue by Alexey-T** [PhotoFlare/photoflare#267]
Lot of graphic editors allow to paint rectangles. Using given line width, color, and using rounded corners (using given radius). I cannot find such a tool here.

Rectangle can also be filled.

**Comment by DylanC** [comment]
@Alexey-T - Yeah. I was working on this feature before. The selection tool had checkboxes for:

- Fill
- Stroke

I didn't have the time to finish my work on it. Hopefully I can get back to this feature soon enough.

**Comment by DylanC** [comment]
@Alexey-T - Resolved in v1.6.13 release.
