### ISSUE TITLE
Misleading error message & behavior: "Incorrect file extension detected" when filename contains "."

### ISSUE THREAD

**Issue by ceefour** [PhotoFlare/photoflare#268]
**Describe the bug**
Misleading error message & behavior: "Incorrect file extension detected" when filename contains "."

**To Reproduce**
1. Open a file named, e.g. `Something 2.8a something.png`
2. Shows: "Incorrect file extension detected"
3. If you click "Save", then file becomes `Something 2.png`

Incorrect behavior because PhotoFlare assumed the extension is `.8a something.png` instead of `.png`

**Expected behavior**
Opens file normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/24123/93660639-311b1000-fa7b-11ea-878c-8c758ed5bc3b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 64bit
 - Version 1.6.2 64bit

**Additional context**

Related to #89.

**Comment by DylanC** [comment]
Fixed via: 742866d
