### ISSUE TITLE
Interface bugs

### ISSUE THREAD

**Issue by lionshilov** [PhotoFlare/photoflare#270]
*Interface bugs*

**Bug №1**
Inability to switch between images with a long title.

**To Reproduce**
1. Select and open an image with a long name
2. Select and open another image in the program
3. We try to switch between them, but it doesn't work

**Expected behavior**
Ability to switch and close images

**Screenshots**
![alt text](https://sun4-10.userapi.com/eXuUABZUDnuxPTI8IBcokFPFoRtio77vpB2PNQ/TPKfg9JN46M.jpg)

**Bug №2**
Incorrect display of properties

1. Click on the "File" tab
2. Click on "Image properties"
3. Get a window with incorrect and unreadable text

**Expected behavior**
Readable and correct text

**Screenshots**
![alt text](https://sun4-15.userapi.com/G3WlX-_KokNp2a0Q8bdlYOBMUPJ6qvs0LCoiCQ/vs-d1AVMbgE.jpg)

**Bug №3**
Crash when using the transparent tool

1. Click on the "Edit" tab
2. Select the "Transperent" tool
3. Set the toleran value above 50
4. Get unexpected crash from the program without error notifications

**Expected behavior**
Using the transparent tool without unexpected crashes

**Screenshots**
![alt text](https://sun4-16.userapi.com/Ae0y0phCpT0eMazC9-jwD7CQGF4-RDTt_Gzj-Q/d2xzd7qcRHE.jpg)

**Desktop:**
 - OS: Windows 10
 - Version: Professional
 - Resolution: 2560x1600

**P.S**
There are often elements with incorrect display of text, this may be due to the fact that there is no optimization for 2560x1600.

**Comment by DylanC** [comment]
@lionshilov - Thanks for your feedback. 👍

**Comment by DylanC** [comment]
1. TODO.
2. TODO.
3. Done. Fixed with a7a94198c61901bef0b278caef2b6742d1bb1013.
