### ISSUE TITLE
Closing the program when using the “Colour Picker” after “Transparent Colour”.

### ISSUE THREAD

**Issue by Jpegly** [PhotoFlare/photoflare#271]
**Describe the bug:**
	Closing the program when using the “Colour Picker” after “Transparent Colour”.

**To Reproduce:**
1.	Start the program;
2.	Open an image;
3.	Image -> Transparent Colour -> Preview -> Cancel;
4.	Use Colour Picker.

**Expected behavior:**
	Pick colours from the image.

**Environment:**
Laptop:
- OS: Windows 10 Pro x64
- Version: 1.6.5 Community Edition

**Comment by DylanC** [comment]
@Jpegly - Wow, this is a bad one. Thanks for the report!

**Comment by DylanC** [comment]
Fixed with this commit: a7a94198c61901bef0b278caef2b6742d1bb1013
