### ISSUE TITLE
“Paint Bucket” fills “Transparent Background” with white paint.

### ISSUE THREAD

**Issue by Jpegly** [PhotoFlare/photoflare#274]
**Describe the bug:**
	“Paint Bucket” fills “Transparent Background” with white paint.

**To Reproduce:**
1.	Start the program;
2.	Open an image with “Transparent Background” (.png);
3.	Use “Paint Bucket” on image.

**Expected behavior:**
	“Paint Bucket” should not change “Transparent Background” on image.

**Screenshots:**
![1](https://user-images.githubusercontent.com/25868036/94793474-b6e87500-0404-11eb-9f16-e01126b5ace5.png)
![2](https://user-images.githubusercontent.com/25868036/94793491-bbad2900-0404-11eb-989e-c938bff53048.png)

**Environment:**
Laptop:
- OS: Windows 10 Pro x64
- Version: 1.6.5 Community Edition

**Comment by DylanC** [comment]
@Jpegly - Thanks for the report. I ran into this issue myself already. Fixed already with this commit. https://github.com/PhotoFlare/photoflare/commit/e200ab75385c1900e3168f28dabbe321894cb38d

**Comment by DylanC** [comment]
Fixed with e200ab75385c1900e3168f28dabbe321894cb38d
