### ISSUE TITLE
User’s settings in the “Preferences/Folders” are reset.

### ISSUE THREAD

**Issue by Jpegly** [PhotoFlare/photoflare#276]
**Describe the bug:**
	User’s settings in the “Preferences/Folders” are reset.

**To Reproduce**:
1.	Start the program;
2.	Tools -> Preferences -> Folders;
3.	Install “Opening folder” and “Saving folder”;
4.	Check “Remember previous opened folder” and “Remember previous save folder”;
5.	Click “OK”;
6.	Close the program;
7.	Start the program;
8.	Close the program;
9.	Start the program;
10.	Tools -> Preferences -> Folders.

**Expected behavior:**
	The program should save user’s settings.

**Environment:**
Laptop:
- OS: Windows 10 Pro x64
- Version: 1.6.5 Community Edition

**Comment by nikonov1996** [comment]
The value of the "Remember previous save folder" checkbox is not saved if you exit and go to settings again. You don't need to close the program to play it bug.
![bandicam_2020-10-04_10-01-36-113](https://user-images.githubusercontent.com/39374425/95005958-c516db00-0628-11eb-97d1-b0d9a7e276e2.gif)

Operating system: Windows 8 x64.
Program version: 1.6.5 Community Edition.

**Comment by DylanC** [comment]
Dup of #196

**Comment by DylanC** [comment]
Fixed in 55a4f07941b8fe2bd4b875fc33504d52c4982cf0
