### ISSUE TITLE
Warning "Incorrect file extension detected" with uppercase image formats.

### ISSUE THREAD

**Issue by full-confession** [PhotoFlare/photoflare#278]
**Describe the bug**
Opening image where file extension contains uppercase letters gives warning "Incorrect file extension detected". If "save" option is selected, image still loads.

**To Reproduce**
1. Open image where file extension contains uppercase letters, e.g. "image.PNG".

**Expected behavior**
No warnings.

**Desktop**
 - OS: Windows 10 Pro, x64, build 19041.508
 - Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@full-confession - True. It should probably just open those.
