### ISSUE TITLE
Getting artifacts when using Contrast or Saturation.

### ISSUE THREAD

**Issue by full-confession** [PhotoFlare/photoflare#279]
**Describe the bug**
When using a contrast or saturation adjustments, three lines appear in the image.

**To Reproduce**
1. Open image.
2. Apply Contrast or Saturation. Can be applied multiple times to increase lines visibility.

**Expected behavior**
Processed image without artifacts.

**Screenshots**
![image](https://user-images.githubusercontent.com/72213267/94834293-65f37380-043a-11eb-9dc1-aa26c6563925.png)

**Desktop**
 - OS: Windows 10 Pro, x64, build 19041.508
 - Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
Fixed in v1.6.8 release.
