### ISSUE TITLE
"Hue variation -> Method2/Hue" doesn't work with black color

### ISSUE THREAD

**Issue by nikonov1996** [PhotoFlare/photoflare#285]
**Description**
The most part of selected colors from color box changes using by "Hue variation -> Method2/Hue" except the black color

**To Reproduce**
1. Create image with colors from color box (including black color)
2. Click on 'Adjust -> Hue variation -> Method2/Hue'
3. Use slider to change colors
4. Look that black color doesn't change

**Expected behavior**
All colors change how it works with method 1.

**Screenshots**
![bandicam_2020-10-04_05-51-12-253](https://user-images.githubusercontent.com/39374425/95003248-950b1000-0607-11eb-80c6-01af7df5a76a.gif)

Operating system: Windows 8 x64.
Program version: 1.6.5 Community Edition.

**Comment by DylanC** [comment]
![Peek 2020-10-23 17-15](https://user-images.githubusercontent.com/4488048/97027971-61127300-1553-11eb-8160-fa18ba3370c2.gif)

This is also how it works in GIMP. ^
