### ISSUE TITLE
Inconvenient switching of the "Opacity" value

### ISSUE THREAD

**Issue by nikonov1996** [PhotoFlare/photoflare#286]
**Description**
The opacity value is decimal fraction from 0.0 to 1.0 . The arrows for change opacity value changes number before point, but it should change the number after point in decimal fraction.

**To Reproduce**
1. Go to 'Adjust -> Opacity..'
2. Click on opacity change arrows
3. Look how opacity value changes

**Expected behavior**
The opacity change arrows gradually change the opacity value. Digits after the decimal point must be changed when arrows clicked.

**Screenshots**
![bandicam_2020-10-04_06-18-38-883](https://user-images.githubusercontent.com/39374425/95003723-22e8fa00-060c-11eb-899f-17307f17d57e.gif)

Operating system: Windows 8 x64.
Program version: 1.6.5 Community Edition.

**Comment by DylanC** [comment]
Fixed via a7bb402514a1fb8eed46abf4df44626a31281e74.
