### ISSUE TITLE
Versions on website and in programm differ

### ISSUE THREAD

**Issue by Nirowe** [PhotoFlare/photoflare#293]
**Describe the bug**
The versions on the website and in the program description differ. On the website version 1.6.5, in the description of the program in "Help"->"About" version 1.6.6

**To Reproduce**
1. Go to 'help'
2. Click on 'about'
3. Compare version on the website (http://photoflare.io/downloads/), version in program and in readme 
4. See diff

**Expected behavior**
The versions on the sites and in the description must match

**Screenshots**
![Снимок экрана от 2020-10-07 13-13-25](https://user-images.githubusercontent.com/38606022/95294181-06b0bb80-089f-11eb-9bb5-e70514059f38.png)

http://photoflare.io/downloads/
![Снимок экрана от 2020-10-07 13-20-16](https://user-images.githubusercontent.com/38606022/95294669-e6353100-089f-11eb-83ea-c3d5aeb64c5d.png)

**Desktop**
 - OS: Ubuntu 20.04 x64
 - Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@Nirowe - Where did you install Photoflare from? I can't find this problem.

**Comment by Nirowe** [comment]
I used the command:
sudo add-apt-repository ppa:photoflare/photoflare-stable
sudo apt-get update
sudo apt install photoflare

**Comment by DylanC** [comment]
I used those commands in a fresh version of xUbuntu 20.04. This is the result:
![image](https://user-images.githubusercontent.com/4488048/96839568-494aca00-1441-11eb-8232-3e23627a5f0f.png)

Let me know if there is any other way to see this issue.
