### ISSUE TITLE
Incorrect rotation in 'Tools' -> 'Automate/Batch' -> 'Transform'

### ISSUE THREAD

**Issue by Nirowe** [PhotoFlare/photoflare#296]
**Describe the bug**
Position when using 'Automate/Batch' -> 'Transform' without rotation, the image rotates 90 degrees clockwise. When using 'Rotate 180', the image is in its normal position

**To Reproduce**
1. Go to 'Tools -> Automate/Batch'
2. In “Files” add image file
3. In “Transform” don’t  use “Rotate” 
4. Click “ok”
5. See image rotates 90 CW
6. In “Files” add image file
7. In “Transform” use “Rotate 90” 
8. See image rotates 90 CW
9. In “Files” add image file
10. In “Transform” use “Rotate 180” 
11. See images in normal position

**Expected behavior**
The image should rotate if “Rotate” is not selected; the image should rotate 180 degrees if “Rotate on 180” is selected

**Screenshots**
![rotate-bug-1](https://user-images.githubusercontent.com/38606022/95310688-e7258d00-08b6-11eb-9804-55bf2df266e4.gif)

**Desktop**
 - OS: Ubuntu 20.04  x64
 - Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
Dup of #266 
Fixed in commit 0f9195fb5fe7e05589ee49195d6c547a725a5be7.
