### ISSUE TITLE
The 'ctrl'+'+' hotkey doesn't work

### ISSUE THREAD

**Issue by Nirowe** [PhotoFlare/photoflare#297]
**Describe the bug**
The 'ctrl' + '+' hotkey doesn't work. 

**To Reproduce**
1. Open or create image
2. Push “ctrl” and “+”
3. See the zoom in don’t work

**Expected behavior**
Push “ctrl” and “+” zoom in to the image

**Desktop**
 - OS: Ubuntu 20.04  x64
 - Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@Nirowe - I guess the shortcut is using [Ctrl+Shift+Plus] together at the moment. Should just be Ctrl+Plus key without using the shift key.

**Comment by DylanC** [comment]
@Nirowe - Not sure if I can solve this one:
https://doc.qt.io/qt-5/qkeysequence.html#keyboard-layout-issues

It seems if you don't stick to using the default zoomin shortcut this can create issues for people with other keyboard layouts.
