### ISSUE TITLE
The program closes when the 'Transparent color' window is closed

### ISSUE THREAD

**Issue by Nirowe** [PhotoFlare/photoflare#298]
**Describe the bug**

**To Reproduce**
1. Open image file
2. Go to 'Transparent color'
3. Close the 'Transparent color' window
4. See the program is closed

**Expected behavior**
'Transparent color' window should close and the program should continue working

**Screenshots**
![transparent-bug](https://user-images.githubusercontent.com/38606022/95312908-b6932280-08b9-11eb-934f-9e3afdcb4c3f.gif)

**Desktop**
 - OS: Ubuntu 20.04  x64
 - Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
Dup of #271
