### ISSUE TITLE
Text size 0 is incorrect.

### ISSUE THREAD

**Issue by aslatyshev** [PhotoFlare/photoflare#299]
#**Describe the bug**
Text size 0 is incorrect.

**To Reproduce**
1. Go to Start Photoflare
2. Click on Button Text
3. Select size equal to 0
4. Write text with dimensions other than 0
5. See that font size 0 is greater than 10 and less than 15

**Expected behavior**
it was assumed that the text would be impossible to create or it would be less than 1

**Screenshots**
![Photoflare(textSize)2020-10-07_16-16](https://user-images.githubusercontent.com/60701820/95312896-b430c880-08b9-11eb-9ae8-9ae2f79b5af3.png)
`

**Desktop (please complete the following information):**
 - OS: [Linux Mint 20 x86_64]
 - Version [1.6.5]

**Additional context**
Very pixelated text

**Comment by DylanC** [comment]
@aslatyshev - Thanks for the report. Pixelated text is due to the zoom level. Should look fine if zoom = 100%.
