### ISSUE TITLE
Hue variation color select.

### ISSUE THREAD

**Issue by sobujbd** [PhotoFlare/photoflare#30]
Method 1 / Colorise - Working :white_check_mark: 
Method 2 / Hue - Not Working :x:

On color select `horizontalSlider degrees` need to be adjust.

**Comment by DylanC** [comment]
@sobujbd - What do you mean? Do you have an example?

**Comment by sobujbd** [comment]
See this as example.
![photoflare 2017-12-14 12-02](https://user-images.githubusercontent.com/16955338/33977840-03dd380a-e0c7-11e7-9c98-08de3ae0b1e3.gif)

**Comment by DylanC** [comment]
@sobujbd - Thanks. I will give this a test. Looks like a possible bug here.

**Comment by DylanC** [comment]
@sobujbd - Yes, this is a problem with the current version. Thanks.

**Comment by DylanC** [comment]
@sobujbd - Just to give you some background on this.

The feature of selecting a custom colour was added as part of a community suggestion. 
https://photoflare.io/photofiltre-lx-1-0-1-released/

This is why the degrees do not get updated. I'm not exactly sure how to convert a colour to degrees, as I'm pretty sure the degrees depends upon the slider value and not the actual colour.

**Comment by DylanC** [comment]
@sobujbd - I was thinking of changing the degrees label to say "Custom" if you pick a custom colour. How does this sound as a workaround?

**Comment by sobujbd** [comment]
You can hide the degrees
or Show an Icon
or Show color code 
or Show color name
Or for now 'custom'.
In 30 px what will be good, do you think?

**Comment by DylanC** [comment]
@sobujbd - Yes, I think any option from that list would be good.

**Comment by DylanC** [comment]
Added a fix for this: 6b6fb2a1eeab2e3e65178d422782634bd15ff124
