### ISSUE TITLE
Brush invisible

### ISSUE THREAD

**Issue by aslatyshev** [PhotoFlare/photoflare#304]
**Describe the bug**
Brush invisible

**To Reproduce**
1. Go to Start Photoflare
2. Click on paint brush
3. The brush frame is almost invisible

**Expected behavior**
Need to make it wider

**Screenshots**
NO 

**Desktop (please complete the following information):**
 - OS: [Linux Mint 20 x86_64]
 - Version [1.6.5]

**Additional context**

**Comment by DylanC** [comment]
@aslatyshev - Do you expect the default size to be bigger than 1?
