### ISSUE TITLE
Setting the radius of a square 'Eraser Tool'

### ISSUE THREAD

**Issue by Nirowe** [PhotoFlare/photoflare#306]
**Describe the bug**
To customize the size of the 'Eraser Tool' the concept of 'Radius' is used

**To Reproduce**
1. Open image
2. Click on  'Eraser Tool' 
3. See form eraser and settings of 'Eraser Tool'

**Expected behavior**
The shape of the eraser must be a circle OR the size is described by a diagonal or side

**Screenshots**
![radius](https://user-images.githubusercontent.com/38606022/95351265-3c7b9180-08eb-11eb-9557-55d7580248af.png)

**Desktop**
 - OS: Ubuntu 20.04  x64
 - Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@Nirowe - You mean to use an alternative word for radius here?

**Comment by Nirowe** [comment]
Yes. "diagonal" maybe
