### ISSUE TITLE
The color of using the 'Eraser tool' does not change

### ISSUE THREAD

**Issue by Nirowe** [PhotoFlare/photoflare#307]
**Describe the bug**
The colour of using the eraser does not change if you change the second colour

**To Reproduce**
1. Open some image
2. Click on 'Eraser Tool'
3. Click on some colour (not white) for second colour
4. Use eraser
5. See white after using

**Expected behavior**
After using the eraser, a second colour appears

**Screenshots**
![eraser-color-bug](https://user-images.githubusercontent.com/38606022/95352612-9761b880-08ec-11eb-99b3-3c4b4d2adf0d.gif)

**Desktop**
 - OS: Ubuntu 20.04  x64
 - Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@Nirowe - Does this behaviour happen in any other image editors?

**Comment by Nirowe** [comment]
In other image editors, if it is possible to select two colors, the second color is used when using the eraser
![изображение](https://user-images.githubusercontent.com/38606022/97087594-6fe14e80-1655-11eb-940c-ab29a64212f4.png)
![изображение](https://user-images.githubusercontent.com/38606022/97087621-9b643900-1655-11eb-8c72-b2ba2c86d52e.png)
