### ISSUE TITLE
...

### ISSUE THREAD

**Issue by sobujbd** [PhotoFlare/photoflare#31]
PhotoFlare now available on AlternativeTo.
[PhotoFlare Alternatives and Similar Software - AlternativeTo.net](https://alternativeto.net/software/photoflare/)

Also submitted on Slant (Best software comparison site) - Choose the best.
[PhotoFlare - What is the best photo editing software? - Slant](https://www.slant.co/topics/1188/viewpoints/24/~photo-editing-software~photoflare)

**Comment by DylanC** [comment]
@sobujbd - Thanks. You could have put this in #24 as a comment if you wanted.
