### ISSUE TITLE
"Dust Reduction" artifacts

### ISSUE THREAD

**Issue by Hugiwield7** [PhotoFlare/photoflare#312]
**Describe the bug**
Artifacts appear when using the "Dust Reduction" tool. It is also clearly visible if use many times: "Gamma correct", "Saturation" or "Contrast"

**To Reproduce**
1. Open PhotoFlare
2. Open image
3. Click on "Dust Reduction" or "Gamma correct" or "Saturation" or "Contrast"

**Expected behavior**
Artifacts do not appear when using tools

**Screenshots**
Dust Reduction
![dust_reduction](https://user-images.githubusercontent.com/51943163/97302356-85d85480-188b-11eb-8e94-7244cfe2dcd4.png)

Gamma Correct
![gamma_correct](https://user-images.githubusercontent.com/51943163/97302570-d8b20c00-188b-11eb-95d6-58760e20ebca.png)

Saturation
![Saturation](https://user-images.githubusercontent.com/51943163/97302810-2169c500-188c-11eb-9a2e-79ef6d0cc371.png)

Contrast
![contrast](https://user-images.githubusercontent.com/51943163/97302826-26c70f80-188c-11eb-826a-a3cf4e4cea90.png)

**Desktop:**
- OS: Windows 10 Pro x64 build 18363.1139
- Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
Fixed in v1.6.8 release.
