### ISSUE TITLE
Brightness bug in image with transparent background

### ISSUE THREAD

**Issue by Hugiwield7** [PhotoFlare/photoflare#313]
**Describe the bug**
If you download an image with a transparent background, open it and increase or decrease the brightness, the background will turn black.

**To Reproduce**
1. Download any image with transparent backgroud in png format
2. Open PhotoFlare
3. Open downloaded image
4. Click on "Brightness (-)" or "Brightness (+)"

**Expected behavior**
The brightness of the image increased or decreased without affecting the background

**Screenshots**
![Photoflare 2020-10-27 11-34-01](https://user-images.githubusercontent.com/51943163/97303807-7954fb80-188d-11eb-8f2d-04c4520d2e1b.gif)

**Desktop:**
- OS: Windows 10 Pro x64 build 18363.1139
- Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
Fix for #316 solves this issue too.
