### ISSUE TITLE
Using colour picker leads to application crash

### ISSUE THREAD

**Issue by weviro** [PhotoFlare/photoflare#319]
**Description**
The application closes after using a colour picker on a file processed with a transparent colour

**Steps to reproduce the behavior:**
1. Open Photoflare
2. Press Ctrl + N
3. Press "OK" button
4. Use "Transparent Colour"
5. Use "Colour Picker"
6. See crash

**Expected behavior**
Selected color without transparency

**Desktop:**
- OS: Windows 10 Home
- Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@weviro - Fixed in #271. This fix will be in the next release.
