### ISSUE TITLE
Image isn't loading after extension update

### ISSUE THREAD

**Issue by weviro** [PhotoFlare/photoflare#321]
**Description**
Image with changed extension isn't loading after extension update

**Steps to reproduce the behavior:**
1. Change extension of any image with .png extension to .ico
2. Open Photoflare
3. Press Ctrl + O
4. Choose image
5. Press "Open" button
6. Press "Save" button in "Incorrect file extension detected" dialog.
6. See empty space

**Expected behavior**
Image loaded

**Desktop:**
- OS: Windows 10 Home
- Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@weviro - Did you not get this dialog? "Incorrect file extension detected"
![image](https://user-images.githubusercontent.com/4488048/97682591-14b5be80-1a90-11eb-9852-1a1bdc128135.png)

If you click Save the image will open with the extension fixed. Eg. Mine went from .ico to .jpg.

**Comment by weviro** [comment]
@DylanC Sorry, i forgot to write this in bug report. Yes, I got this dialog. There was empty space after it.

**Comment by DylanC** [comment]
@weviro - No problem. I'll try to produce this with a .png.

**Comment by DylanC** [comment]
@weviro - On Linux, I tested with .ico on a .png file and it correctly updated the file to .png. Perhaps I'll need to test this one on Windows.

**Comment by DylanC** [comment]
@weviro - Can you try v1.6.6 portable to confirm if you still have this issue?
https://launchpad.net/photofiltre-lx/trunk/v1.6.6/+download/Photoflare_CE_1.6.6_amd64_win_portable.zip
