### ISSUE TITLE
Language change leads to application crash

### ISSUE THREAD

**Issue by weviro** [PhotoFlare/photoflare#322]
**Description**
Attempt to change the language while a file is open will cause the app crash.

**Steps to reproduce the behavior:**
1. Open Photoflare
2. Press Ctrl + N
3. Press "OK" button
4. Go to 'Tools' -> 'Preferences' -> 'Startup'
5. Change language
6. Press "Restart to apply"
7. See app crash

**Expected behavior**
App restarted

**Desktop:**
- OS: Windows 10 Home
- Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@weviro - Thanks for this report!
