### ISSUE TITLE
The program terminates when using Colour Picker after using Transparent Colour.

### ISSUE THREAD

**Issue by Salazor** [PhotoFlare/photoflare#324]
**Description**
After using the Transparent Colour tool, using the Colour Picker tool terminates the program.

**Severity**
Critical

**Steps to reproduce the behavior:**
1. Open Photoflare
2. Create a new image
3. Use the "Transparent Colour" tool
4. Use the "Colour Picker" tool. 

**Expected behavior**
Selects a colour despite its transparency.

**Actual behavior**
The program terminates and the working window closes.

**Link to gif**
[https://gifyu.com/image/RY6F](url)
[https://gifyu.com/image/RYj1](url)

**Desktop:**
 - OS: Windows 10 Pro
 - Photoflare Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@Salazor - This issue has been fixed recently. a7a94198c61901bef0b278caef2b6742d1bb1013

**Comment by Salazor** [comment]
> @Salazor - This issue has been fixed recently. [a7a9419](https://github.com/PhotoFlare/photoflare/commit/a7a94198c61901bef0b278caef2b6742d1bb1013)

Hello! I have a problem with using "Color Picker" after using "Transparent Color". This fix is not yet uploaded to the current version?

**Comment by DylanC** [comment]
@Salazor - Yes, the fix is not in the current version. It will be released in the next version. (v1.6.6)

**Comment by DylanC** [comment]
Dup of #298. Fix will also fix this bug.
