### ISSUE TITLE
The "Opening folder" and "Saving folder" settings are cleared when you open a file from another folder.

### ISSUE THREAD

**Issue by Salazor** [PhotoFlare/photoflare#329]
**Describe the bug**
If the "Opening folder" and "Saving folder" settings are set in the "Preferences" tool, then if a file is opened from another folder, these settings will be reset when the program is restarted.

**Severity**
Minor

**To Reproduce**
Presets: 
The "Opening folder" and "Saving folder" settings in the "Preferences" tool have been set (without setting "Remember previous opened folder").
1. Open Photoflare.
2. Press ctrl + O (The folder specified as "Opening folder" is opened).
3. Open an image file from a folder other than "Opening folder".
3. Close Photoflare.
4. Open Photoflare.
5. Press ctrl + O.

**Expected behavior**
The folder specified as "Opening folder" is opened.

**Actual behavior**
The default folder opens. In the "Preferences" tool, the "Opening folder" and "Saving folder" settings have been reset.

**Gif**
![5](https://user-images.githubusercontent.com/71212044/98194840-de29e900-1f52-11eb-86ff-36b40ee768e7.gif)

**Desktop:**
- OS: Windows 10 Pro
- Photoflare Version 1.6.5 Community Edition

**Comment by DylanC** [comment]
@Salazor - Would this issue sound similar to #196 ?

**Comment by Salazor** [comment]
> @Salazor - Would this issue sound similar to #196 ?
I checked it out. Indeed, in any case, it resets the settings on the third launch.

**Comment by DylanC** [comment]
Fixed in 55a4f07941b8fe2bd4b875fc33504d52c4982cf0
