### ISSUE TITLE
Incorrect display of image.

### ISSUE THREAD

**Issue by MugiChu** [PhotoFlare/photoflare#331]
**Describe the bug**
A 100x100 drawing was created when zooming in the drawing is not displayed correctly.

**To Reproduce**
1. Ctrl+N
2. Setting the size 100x100
3. Click on the create button
4. Zoom in on the drawing
5. Drawing a picture
6. See error

**Expected behavior**
The correct display of the figure.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/29030475/99153877-1dd49b80-26de-11eb-8b33-a2a0e3a172e6.png)
![изображение](https://user-images.githubusercontent.com/29030475/99153879-24fba980-26de-11eb-933f-0eeb742c7925.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20 Cinnamon
 - Version 4.6.7

**Additional context**
sometimes there are traces of the brush on the background (outside the image).

**Comment by DylanC** [comment]
@MugiChu - This does not happen on PopOS 20.10. (Ubuntu 20.10) I will try Mint 20.

**Comment by DylanC** [comment]
@MugiChu - This did not happen for me on Mint 20.
