### ISSUE TITLE
When you switch to Russian language, not the entire interface changes

### ISSUE THREAD

**Issue by MugiChu** [PhotoFlare/photoflare#332]
**Describe the bug**
When you change the language changes do not affect all functions and buttons many remain without translation.

**To Reproduce**
1. Click on the settings button
2. Open the startup tab
3. Choosing a language(I chose Russian)
4. Restart application
5. Open application
6. Click on the settings button
7. See Error

**Expected behavior**
All tabs and functions will be translated.

**Screenshots**

![изображение](https://user-images.githubusercontent.com/29030475/99154364-c3d5d500-26e1-11eb-9ddb-8b8b13bfc992.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20 Cinnamon
 - Version 4.6.7

**Additional context**
As you can see in the screenshot when the language is set we only have a partial translation.

**Comment by DylanC** [comment]
@MugiChu - If you change to other languages does it work?

**Comment by DylanC** [comment]
Confirmed.

**Comment by DylanC** [comment]
Fixed via v1.6.7 release.
