### ISSUE TITLE
Custom Icon Themes [Question]

### ISSUE THREAD

**Issue by rstreeter** [PhotoFlare/photoflare#336]
I was wondering if it would be possible to add support for custom icon theming for the app interface.

I would like to see [Papirus Icon Theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) I think it would be a good fit. 
All around custom icon theming would be awesome but as a simpler icon theme the above would be a good testing ground.

**Comment by DylanC** [comment]
@rstreeter - This is a great idea. I'll be looking into this soon. 👍
