### ISSUE TITLE
Incomplete localization - Russian

### ISSUE THREAD

**Issue by IrinaB1** [PhotoFlare/photoflare#338]
**Describe the bug**
Incomplete localization

**Severity**
Major

**To Reproduce**
1. Open Photoflare.
2. Use "Tools->Preferences->Startup->Language"" in the top menu of the program.
3. In the window that opens, choose Russian and click the "Restart to apply" button.

**Expected behavior**
Russian language

**Actual behavior**
English language

**Screenshots**
![attachment2](https://user-images.githubusercontent.com/74752458/99756199-2a625500-2b1f-11eb-8ca5-5e988335ea05.png)

**Desktop (please complete the following information):**
OS: Windows 10 Pro
Photoflare Version 1.6.6 Community Edition

**Additional context**
if choose chinese (cn) and click the "Restart to apply" button, we have attachment3.png
![attachment3](https://user-images.githubusercontent.com/74752458/99756210-35b58080-2b1f-11eb-82c9-f4e5feebb43b.png)

**Comment by DylanC** [comment]
Dup of #332

**Comment by DylanC** [comment]
Fixed via v1.6.7 release.
