### ISSUE TITLE
Language selection doesn't work

### ISSUE THREAD

**Issue by nerdouille** [PhotoFlare/photoflare#34]
Hi,
I'm using Debian 9, installed the dependencies and compiled the project using Qt Creator.
Everything went smooth except the language selection doesn't seem to work, after selecting french and clicking OK, the interface stays in english. Nothing is printed in the console.

Any ideas? Thanks :)

**Comment by DylanC** [comment]
@nerdouille - Did you restart the application afterwards? At the moment the language does not update instantly.

**Comment by nerdouille** [comment]
Yes I have, the displayed language in Preference -> Startup is French, but the GUI is still in english

**Comment by DylanC** [comment]
@nerdouille - Sounds like an issue then. I will investigate for the next release.

**Comment by nerdouille** [comment]
Okay thanks, let me know if you want to test stuff on debian, I have basic c++ knowledge :)

**Comment by DylanC** [comment]
@nerdouille - Thanks. I do need to improve on the language selection. In particular I was trying to get it to auto update after you change the selection. 

It proved to be rather tricky but I may give it another shot. In this case however, it looks like a bug with the existing functionality.

**Comment by DylanC** [comment]
@nerdouille - This is still working on Ubuntu 17.10. Maybe I will need to try Debian 9.

**Comment by DylanC** [comment]
@nerdouille - I think this is because its looking for the path:

/usr/share/photoflare/Photoflare/languages/

This is the path the .deb package installs them to.

**Comment by DylanC** [comment]
@nerdouille - I will put in a fix for this.

**Comment by nerdouille** [comment]
@DylanC okay thanks :)

**Comment by DylanC** [comment]
@nerdouille 

I've added a fix (ee1c0ce8ba8deb5df3d6b28eceb0331c4916196c). Can you try this on your Arch and let me know if it works. Thanks.

**Comment by DylanC** [comment]
@nerdouille 
Added another fix (060909d89117062096dabe31d24ab05c50d1a56a)

Just make sure to paste the languages folder into the same directory as the executable.

**Comment by nerdouille** [comment]
@DylanC Thanks, I will try this on saturday, I don't have access to it right now

**Comment by nerdouille** [comment]
All working, thanks :)

**Comment by DylanC** [comment]
@nerdouille - You are very welcome! :)

**Comment by othias** [comment]
Hello, it's me again :) I'm back with the same issue, I just built 1.6.7.1 from source, everything works but language selection doesn't seem to have any effect. the 'languages' directory is next to the photoflare binary, I have also tried copy this directory to /usr/share/photoflare/Photoflare/languages/ but still not working :S no errors shown in the console output either. Any idea ? Thanks
