### ISSUE TITLE
Artifacts appear when zooming 

### ISSUE THREAD

**Issue by IrinaB1** [PhotoFlare/photoflare#340]
**Describe the bug**
Artifacts appear when zooming 

**Severity**
major

**To Reproduce**
1. Open Photoflare.
2. Use "File->Open"" in the top menu of the program.
3. In the window that opens, choose 4bac_1.jpeg and click the "open" button.
4. Choose "gray scale"
5. Choose "contrast +"
6. Start zoom

**Expected behavior**
Artifacts not appear when zooming

**Actual behavior**
Artifacts appear when zooming

**Screenshots**
![attachment6](https://user-images.githubusercontent.com/74752458/99756439-c12f1180-2b1f-11eb-87bd-42189ae5722e.gif)

**Desktop (please complete the following information):**
OS: Windows 10 Pro
Photoflare Version 1.6.6 Community Edition

**Comment by DylanC** [comment]
Fixed in v1.6.8 release.
