### ISSUE TITLE
Position option and Colour in menu Resize Canvas do nothing

### ISSUE THREAD

**Issue by EfremkinAV** [PhotoFlare/photoflare#346]
**Describe the bug**
Position option and colour in Resize Canvas do nothing

**To Reproduce**
1. open/create the file
2. RMB Click on picture, then 'Canvas Size'
3. Choose some position and/or colour, then OK
4. Nothing has happened
5. RMB Click on picture, then 'Canvas Size'
6. All your changes will lost

**Expected behavior**
Canvas Size - Colour must change canvas color
Canvas Size - Position must change canvas position

**Desktop (please complete the following information):**
 
    OS: Windows 10 Pro
    Version 20H2
    Build 19042.630

Additional context
PhotoFlare ver. 1.6.6 community edition

**Comment by DylanC** [comment]
@EfremkinAV - Those options do work:
![image](https://user-images.githubusercontent.com/4488048/106195162-ad4efe00-61a7-11eb-9b5f-c82c7df4c7fa.png)

You probably needed to increase the picture dimensions.
