### ISSUE TITLE
The file opens empty if you change the extension to .jpg

### ISSUE THREAD

**Issue by EfremkinAV** [PhotoFlare/photoflare#347]
**Describe the bug**
The file opens empty if you change the extension to .jpg from .png, .gif e.g.

**To Reproduce**
1. find or create image with extention .png
2. Change extention manualy (for example in windows explorer) from .png to .jpg
3. open this file in Photoflare
4. See empty window

**Expected behavior**
Image should be open correctly (GIMP or Paint open its fine) or should be message about incorrect file or extention

**Screenshots**
![изображение](https://user-images.githubusercontent.com/75077485/100412409-34e49780-30a7-11eb-9d25-bad3da8b8365.png)

OS: Windows 10 Pro
Version 20H2
Build 19042.630

Additional context
PhotoFlare ver. 1.6.6 community edition

**Comment by DylanC** [comment]
@EfremkinAV - My development laptop is currently broken but when the new part arrives  I will have a look at this issue.

**Comment by DylanC** [comment]
@EfremkinAV - The rename from .jpg to .png seems to fail in this case. 👍
