### ISSUE TITLE
Inverted Mouse Scroll

### ISSUE THREAD

**Issue by icenhancer** [PhotoFlare/photoflare#353]
**Describe the bug**
Inverted zoom scroll
[Bug-report - Inverted Scroll.docx](https://github.com/PhotoFlare/photoflare/files/5611112/Bug-report.-.Inverted.Scroll.docx)

**To Reproduce**
1. Open portable app for Windows
2. Open any photo like (3356x5036px) in File section
3. Try to scroll forward with Mouse Scroll
4. See Zoom minus instead of Zoom plus

**Expected behavior**
Scroll forward will plus Zoom

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Version 1.6.6 Portable

**Additional context**

**Comment by DylanC** [comment]
@icenhancer - The default zoom direction is intentional.
![image](https://user-images.githubusercontent.com/4488048/119980207-e0699880-bfb3-11eb-9a86-d353964d4ea6.png)

You can always change this in the Preferences.
