### ISSUE TITLE
Fails to build on archlinux with qt5-5.10.0

### ISSUE THREAD

**Issue by mmetak** [PhotoFlare/photoflare#36]
```
Project ERROR: This project requires Qt 5.6.0 or later
```

**Comment by DylanC** [comment]
@mmetak - I think certain features are only in Qt 5.6. If you want you can try to change the top line in 

**Photoflare.pro**

`lessThan(QT_VERSION, 5.6.0): error(This project requires Qt 5.6.0 or later)`

to

`lessThan(QT_VERSION, 5.5.0): error(This project requires Qt 5.5.0 or later)`

However, I think this will result in an error.

**Comment by mmetak** [comment]
With that I get the same error. Commenting out that line and it builds and runs fine though...

Is there any particular reason it can't build on qt-5.10.0? It ran just fine until this latest stable release of qt5.
Versions 5.5.0>5.6>5.7>5.8>5.9.

**Comment by DylanC** [comment]
@mmetak - Oh I did read your initial report wrong. 5.10 is indeed newer. Strange how the latest qt5 gives a problem with the check in the .pro file.

I will investigate this issue and see is there a reason the check now fails.

**Comment by mmetak** [comment]
https://bugreports.qt.io/browse/QTBUG-63325

**Comment by DylanC** [comment]
@mmetak - Ah I see. Looks like we need to use versionAtLeast for the comparison going forward.

**Comment by DylanC** [comment]
@mmetak - A fix has been merged in for this. Working on old and new version of Qt. :)
