### ISSUE TITLE
Unable to open tiff file

### ISSUE THREAD

**Issue by MariaVPetrenko** [PhotoFlare/photoflare#364]
**Describe the bug**
Unable to open tiff file using the menu, buttons and keyboard shortcut

**To Reproduce**
1. Click on "File >> Open..." or button in the form of a folder with a green arrow or press "Ctrl+O"
2. Choose any file in the tiff format
3. Click on button "Open"

**Expected behavior**
File in the tiff format will be opened

**Screenshots**
![image](https://user-images.githubusercontent.com/77792405/105373198-00b9cd00-5c39-11eb-8544-5d10dcde11cd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1909

**Comment by DylanC** [comment]
@MariaVPetrenko - Fixed via 2641e227c37f5949c27e46ee928a1fb41aab7fb7
