### ISSUE TITLE
Invalid keyboard shortcut for adjusting hue

### ISSUE THREAD

**Issue by MariaVPetrenko** [PhotoFlare/photoflare#365]
**Describe the bug**
Invalid keyboard shortcut for adjusting hue

**To Reproduce**
1. Try to adjusting hue with keyboard shortcut "Ctrl+H"
2. See error 

**Expected behavior**
The area with hue variation will be opened

**Screenshots**
The actual result:
![image](https://user-images.githubusercontent.com/77792405/105378805-c4896b00-5c3e-11eb-93df-dd2b939ad4f1.png)

**Desktop:**
 - OS: Windows
 - Version 1909

**Comment by DylanC** [comment]
Ctrl+H - "Launch the Resize image dialog." 

Keyboard shortcuts are available in the docs.
https://photoflare.github.io/photoflare/allshortcuts.html
