### ISSUE TITLE
Scale level constants are out of order

### ISSUE THREAD

**Issue by MariaVPetrenko** [PhotoFlare/photoflare#367]
**Describe the bug**
Scale level constants are out of order

**To Reproduce**
1. Click on scale`s area
2. See the drop-down list end the error in it

**Expected behavior**
the scale options will be arranged in order

**Screenshots**
![image](https://user-images.githubusercontent.com/77792405/105389973-1afca680-5c4b-11eb-8e68-d91fff48786c.png)

**Desktop:**
OS: Windows
Version 1909

**Comment by DylanC** [comment]
They are in order for me:
![image](https://user-images.githubusercontent.com/4488048/109391585-bbf81480-790f-11eb-845f-15bf086f28de.png)

What version of PhotoFlare is this?
