### ISSUE TITLE
The application has no russian localization

### ISSUE THREAD

**Issue by moris82** [PhotoFlare/photoflare#368]
**Describe the bug**
The application has no russian localization

**To Reproduce**
1. Go to the tab “Preferences”
2. Open the tab “Startup”
3. Choose Russian language from drop-down list
4. Click the button “Restart to apply”

**Actual result:**
The language of the application does not change to Russian

**Expected result:**
Language of the application should change to Russian

**Desktop:**
 - OS:OS Windows 10 Pro 64
 - Version 2004, Build 19041.746

**Comment by DylanC** [comment]
Dup of #332

**Comment by DylanC** [comment]
Fixed via v1.6.7 release.
