### ISSUE TITLE
Strange lines in the picture after using Contrast tool

### ISSUE THREAD

**Issue by moris82** [PhotoFlare/photoflare#370]
**Describe the bug**
Strange lines in the picture after using Contrast tool

**To Reproduce**
1. Open any .jpg file
2. Choose Contrast Minus tool

**Actual result:**
Strange lines appear in the picture. Contrast Minus function is working correctly.

**Expected result:**
Using Contrast Minus function has no strange artifacts.

**Screenshots**
Screenshot_2
![Screenshot_2](https://user-images.githubusercontent.com/51316590/105579211-b874e900-5db7-11eb-8aa2-a5875a46960d.png)

**Desktop:**
 - OS: Windows 10 Pro 64
 -  Version 2004, Build 19041.746

**Additional context**
The same issue with Contrast plus function

**Comment by DylanC** [comment]
Fixed in v1.6.8 release.
