### ISSUE TITLE
 Ctrl ++ zoom does not work in the View tab

### ISSUE THREAD

**Issue by sashahari** [PhotoFlare/photoflare#373]
**Describe the bug**

Ctrl ++ zoom does not work in the View tab.

**Severity**
Critical

**To Reproduce**

1. Open Photoflare.
2. Create a new document (Ctrl+N).
3. Click Ctrl ++ to zoom in.

**Expected behavior**

The scale does not increase.

**Actual behavior**
When pressing Ctrl ++ the scale should increase.

**GIF**
![Ctrl+](https://user-images.githubusercontent.com/78033998/105866856-00e60e00-6027-11eb-88ce-5cd317d93904.gif)

**Desktop:**
Linux (Archlinux)
Windows 10
Photoflare v.1.6.6

**Comment by DylanC** [comment]
Ctrl+Shift+Plus is the shortcut for zoom in:
https://photoflare.github.io/photoflare/allshortcuts.html
