### ISSUE TITLE
Colour Picker Tool got colours from wrong pipette point

### ISSUE THREAD

**Issue by akq6** [PhotoFlare/photoflare#382]
**Description**
Colour Picker Tool picks the colour from middle point of cursor.

**Demonstration**
https://user-images.githubusercontent.com/57383088/106379134-6b5acd80-63dc-11eb-93d1-66b52066ff6b.mp4

**Expected behavior**
Colour should pick from the tip of the pipette.

**Desktop:**
 - OS: Windows 10 Corporate LTSC
 - Version: 1.6.6 Community Edition

**Comment by DylanC** [comment]
Dup of #183
