### ISSUE TITLE
Auto Leveling creates horizontal artifacts or colorize gradients in solid color

### ISSUE THREAD

**Issue by akq6** [PhotoFlare/photoflare#389]
**Description**
Image - Auto Level creates artifacts or colorize in solid color gradients and sky.

**Demonstration**
https://user-images.githubusercontent.com/57383088/106379842-487ee800-63e1-11eb-9771-44a84e4dbb22.mp4

**To Reproduce**
1. Open picture with gradient
2. Click on 'Image - Auto Level'

**Expected behavior**
There shouldn't be so heavy artifacts or solid color filling.

**Desktop:**
 - OS: Windows 10 Corporate LTSC
 - Version: 1.6.6 Community Edition

**Comment by DylanC** [comment]
Fixed in v1.6.8 release.
