### ISSUE TITLE
Transparent colour selection with Colour picker

### ISSUE THREAD

**Issue by akq6** [PhotoFlare/photoflare#392]
**Is your feature request related to a problem? Please describe.**
Right now, Photoflare automatically selects transparent colour in 'Image - Transparent Colour'. And while you saving .png file program doesn't saves transparent BG, replacing it to gray.

**Describe the solution you'd like**
Colour selection with Colour picker! For 'Transparent Colour' and before saving file in .png extension.

**Comment by DylanC** [comment]
@akq6 - Do you have a desktop recording to help me understand what you are looking for? Currently you can already select the correct colour outside this dialog with the colour picker tool:

![image](https://user-images.githubusercontent.com/4488048/120698366-df020980-c4a6-11eb-864e-138aa8ac45d5.png)
