### ISSUE TITLE
System language

### ISSUE THREAD

**Issue by dok1196** [PhotoFlare/photoflare#394]
**Describe the bug**
When choosing Russian. Changes do not take effect

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Preferences'
3. Click on 'Startup'
3. Select to 'Russian' fnd press "ОК"

**Expected behavior**
The program is restarted. Language displayed Russian.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 7
 - Version: 1.6.6

**Additional context**

**Comment by DylanC** [comment]
Dup of #332

**Comment by DylanC** [comment]
Fixed via v1.6.7 release.
