### ISSUE TITLE
Rotate the image after changing the aspect.

### ISSUE THREAD

**Issue by dok1196** [PhotoFlare/photoflare#395]
**Describe the bug**
Rotate the image after changing the aspect.

**To Reproduce**
1. Open the 'Tools'
2. Click on 'Automate/Batch..'
3. Click on 'Add files'
4. Select image
5. Select output format
6. Press OK
7. See error

**Expected behavior**
After the operation The image opens without rotation

**Screenshots**
![баг 2](https://user-images.githubusercontent.com/53541925/107811151-526cf780-6da0-11eb-82d8-955727521ace.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version 1.6.6

**Additional context**

**Comment by DylanC** [comment]
Dup of #266

**Comment by DylanC** [comment]
Fixed in commit 0f9195fb5fe7e05589ee49195d6c547a725a5be7.
