### ISSUE TITLE
Stripes with decreasing saturation

### ISSUE THREAD

**Issue by dok1196** [PhotoFlare/photoflare#396]
**Describe the bug**
Stripes appear when image saturation decreases

**To Reproduce**
1. Open the image.
2. Press "saturation -" for black and white photography
3. See error

**Expected behavior**
The image becomes black and white without stripes

**Screenshots**
![баг 4](https://user-images.githubusercontent.com/53541925/107813234-cb6d4e80-6da2-11eb-894f-4037a38970cf.jpg)

**Desktop (please complete the following information):**
 - OS:  Windows 7
 - Version 1.6.6

**Additional context**

**Comment by DylanC** [comment]
Stripe issue has been fixed in the v1.6.8 release.
https://github.com/PhotoFlare/photoflare/releases/tag/v1.6.8
