### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by GlubokinV** [PhotoFlare/photoflare#399]
**Describe the bug**
When switching the interface language to Russian, the language does not change.

**To Reproduce**
1.	Click on «Tools»
2.	Click on «Preferences»
3.	Switch to the tab «Startup» 
4.	Select the language «Russian»
5.	Click «ok» and restart program or click «Restart to apply»
6.	See the interface language has not changed

**Expected behavior**
Language interface changed to «Russian»

**Screenshots**

![БагПеревода](https://user-images.githubusercontent.com/79124989/108018913-946d9600-704b-11eb-9b24-47932a18afab.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Version [e.g. 1.6.6]

**Additional context**
Localization file is missing in the program folder:
\Photoflare_CE_1.6.6_amd64_win_portable\languages

**Comment by DylanC** [comment]
Dup of #332

**Comment by DylanC** [comment]
Fixed via v1.6.7 release.
