### ISSUE TITLE
Open file error

### ISSUE THREAD

**Issue by GlubokinV** [PhotoFlare/photoflare#402]
**Describe the bug**
When you try to open a file with a dot in its name, an error appears.

**To Reproduce**
1.	Open the file with a dot in the title text
2.	See the error with wrong reason

**Expected behavior**
The file with a dot must open or the error text should report an incorrect file name.

**Screenshots**
![Bug report 10(Некоррект откр файл с точкой в названии)](https://user-images.githubusercontent.com/79124989/108019991-f9c28680-704d-11eb-9fbe-27d7b3831a78.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Version [e.g. 1.6.6]

**Additional context**

**Comment by DylanC** [comment]
https://github.com/PhotoFlare/photoflare/commit/742866dc6ad11c153f0e574c8af6f5e7f4b3b8da
