### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by GlubokinV** [PhotoFlare/photoflare#403]
**Describe the bug**
If you apply the tool «Paint Bucket» to a file that is open with an error, the program will crash. Any changes to the rest of the files will be lost.

**To Reproduce**
1.	Click on «File» 
2.	Click on «Open»
3.	Select a file with a dot in its name
4.	In the pop-up window select «save»
5.	Select tool «Paint Bucken» from tool bar
6.	Apply on an open window that was opened with an error
7.	See the closing of the program

**Expected behavior**
The program should not close

**Screenshots**
![Bug report 11(Завершение работы при использовании инструмента)](https://user-images.githubusercontent.com/79124989/108020228-81a89080-704e-11eb-84ce-f110fab096e4.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Version [e.g. 1.6.6]

**Additional context**

**Comment by DylanC** [comment]
Fixed via: https://github.com/PhotoFlare/photoflare/commit/742866dc6ad11c153f0e574c8af6f5e7f4b3b8da
