### ISSUE TITLE
«Saturation». Stripes.

### ISSUE THREAD

**Issue by GlubokinV** [PhotoFlare/photoflare#408]
**Describe the bug**
Horizontal stripes appear from the function «Saturation»

**To Reproduce**
1.	Open exist picture 
2.	Click on «Saturation»
3.	See the appearance of horizontal stripes

**Expected behavior**
Correct execution of the function «Saturation». No stripes.

**Screenshots**
![Bug report 8(Полосы от функции Saturation) — копия](https://user-images.githubusercontent.com/79124989/108022523-478dbd80-7053-11eb-8dbf-5dd8c9b9a5cf.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Version [e.g. 1.6.6]

**Additional context**

**Comment by DylanC** [comment]
Dup of #396

**Comment by DylanC** [comment]
Stripe issue has been fixed in the v1.6.8 release.
https://github.com/PhotoFlare/photoflare/releases/tag/v1.6.8
