### ISSUE TITLE
Update languages for next release

### ISSUE THREAD

**Issue by DylanC** [PhotoFlare/photoflare#41]
Need to collaborate with our contributors to update the language packs to cover the new screens/features for the upcoming 1.5.1 release.

**Comment by DylanC** [comment]
@Dean-Coakley 

Check this out. Might be able to get the new untranslated strings this way:
https://stackoverflow.com/questions/8513149/merge-translation-files-ts-with-existing-ts-files-using-qt-utilities-lconve

**Comment by nerdouille** [comment]
I can help with french translation if you like

**Comment by DylanC** [comment]
@nerdouille - Sounds good! First we just need an easy way to identify the strings that need translation.  I will get back to you if we need some help with the FR strings.

**Comment by Dean-Coakley** [comment]
@DylanC Tried the above method to no success at all. I will look further into this issue later this week

**Comment by DylanC** [comment]
@Dean-Coakley - No problem. Thanks!

Did you do something like:
```
cd languages/
lconvert -i en.ts de.ts -o newDE.ts
```

**Comment by Dean-Coakley** [comment]
@DylanC Yeah, exactly like that.

I think if you read the above answer you linked you'll understand why it didn't work.

Output
https://gist.github.com/Dean-Coakley/3e92bd9d4f66ab9bf153eeca6536bfae

**Comment by Dean-Coakley** [comment]
@DylanC I created a python script that looks for source strings in en.ts and looks for souce strings that don't exist in fr.ts. Output looks _mostly_ good. Thoughts?

https://gist.github.com/Dean-Coakley/cf97dbd6cb2af92b1787ca3811be9d68

**Comment by DylanC** [comment]
@Dean-Coakley - If its 100% reliable then it sounds good, otherwise i'm not so sure. :)

**Comment by DylanC** [comment]
@nerdouille - Im unsure if my French translator will get back to me. Can you translate these strings for us if possible?

https://gist.github.com/Dean-Coakley/cf97dbd6cb2af92b1787ca3811be9d68

**Comment by DylanC** [comment]
@nerdouille - I have the extra French strings translated already for now but I will keep you in mind for the future!

**Comment by DylanC** [comment]
This is progressing slowly. Focused on getting FR and NL fully up to date first. Then I will need to find a translator for DE to help convert new strings.

**Comment by DylanC** [comment]
FR and NL are completed. Just need to add all missing items to DE .ts file and then find a translator.

**Comment by nerdouille** [comment]
Damn sorry I missed your comment, yes please keep me in mind :)

**Comment by DylanC** [comment]
Just need this last string to be translated I think:
"Please open a valid image file"

Looking for FR and NL translation.

**Comment by nerdouille** [comment]
I'd translate that as "Le fichier à ouvrir doit être une image valide"

**Comment by DylanC** [comment]
@nerdouille - Thanks!

The very last items to be translated are the right click items:

- Save
- Save as
- Close
- Separator
- Copy
- Paste
- Separator
- Image Size
- Canvas Size
- Separator
- Undo
- Redo

**Comment by nerdouille** [comment]
Hey DylanC, here are the translations :)

    Save => Enregistrer
    Save as => Enregistrer sous
    Close => Fermer
    Separator => Séparateur
    Copy => Copier
    Paste => Coller
    Separator => Séparateur
    Image Size => Taille de l'image
    Canvas Size => Taille du canevas
    Separator => Séparateur (is there a specific context to these?)
    Undo => Annuler
    Redo => Refaire

**Comment by DylanC** [comment]
@nerdouille - The separator didn't need to be translated actually. Its just a line between each of the items. Thanks again!
