### ISSUE TITLE
When using automatic / batch - the image is reversed

### ISSUE THREAD

**Issue by rickyticky2** [PhotoFlare/photoflare#413]
**Describe the bug**
When using an automatic / batch - images are flipped 90 degrees without using the rotate function.

**To Reproduce**
1. use an automatic / batch
2. add image
3. set image size
4. press ok and look at the orientation of the image.

**Screenshots**
![Tiwx5NFWSq 1](https://user-images.githubusercontent.com/79316032/108617333-24df1880-7448-11eb-80df-43c1b9cee6d5.gif)

**Expected behavior**
The image should be flipped when using the rotate function.

**Desktop OS**: Windows 10 x64
Version 10.0.19042
CPU - i5 6400
RAM - 16gb.

**Comment by DylanC** [comment]
Dup of #266

**Comment by DylanC** [comment]
Fixed in commit 0f9195fb5fe7e05589ee49195d6c547a725a5be7.
