### ISSUE TITLE
Images are flipped and reflected horizontally during batch loading

### ISSUE THREAD

**Issue by gzvpln** [PhotoFlare/photoflare#424]
**Describe the bug**
If uploading multiple images using batch upload,
they will all flip 90 degrees and be reflected horizontally

**To Reproduce**
1. Select "Automate / Batch" from the menu
2. On the "Files" tab, click on " Add Files"
3. Select multiple images
4. Click on " Ok"

**Expected behavior**
Images should not be flipped or reflected during batch loading

**Screenshots**
![Пакетная загрузка](https://user-images.githubusercontent.com/79362272/108618779-66c18c00-7453-11eb-9e6f-3113e2a97490.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1909

**Additional context**
AMD Risen 5 3500U, 8 GB RAM, x64

**Comment by DylanC** [comment]
Dup of #266

**Comment by DylanC** [comment]
Fixed in commit 0f9195fb5fe7e05589ee49195d6c547a725a5be7.
