### ISSUE TITLE
Fade mode does not work in "Advanced Paint Brush"

### ISSUE THREAD

**Issue by gzvpln** [PhotoFlare/photoflare#425]
**Describe the bug**
The line does not change if you apply the fade mode in "Advanced Paint Brush"

**To Reproduce**
1. Create or open an image
2. Select "Advanced Paint Brush" from the toolbar
3. Drow a line
4. Select the mode "Fade"
3. Drow a line

**Expected behavior**
When using fade mode, the line should gradually become lighter

**Screenshots**

https://user-images.githubusercontent.com/79362272/108618818-b607bc80-7453-11eb-8471-078a50064b81.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1909

**Additional context**
AMD Risen 5 3500U, 8 GB RAM, x64

**Comment by DylanC** [comment]
@gzvpln - It does fade. You have to paint for longer unless you adjust the **Pressure** setting.
