### ISSUE TITLE
The opacity value of the image when using the arrows changes only to 0 or 1

### ISSUE THREAD

**Issue by gzvpln** [PhotoFlare/photoflare#427]
**Describe the bug**
If change the opacity value through the arrows, then its value will not change gradually, but sharply only by 0 and 1

**To Reproduce**
1. Open an image
2. Select "Opacity" from the menu "Adjust"
3. Try changing the value with the arrows

**Expected behavior**
The opacity value will change gradually when you click on the arrows

**Screenshots**

https://user-images.githubusercontent.com/79362272/108618949-7e4d4480-7454-11eb-92ba-e3c28906d65c.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1909

**Additional context**
AMD Risen 5 3500U, 8 GB RAM, x64

**Comment by DylanC** [comment]
Dup of #286

**Comment by DylanC** [comment]
Fixed via a7bb402514a1fb8eed46abf4df44626a31281e74.
