### ISSUE TITLE
The language does not change to Russian

### ISSUE THREAD

**Issue by vladz99** [PhotoFlare/photoflare#429]
**Describe the bug**
If you change the language to Russian, the program does not save the changes when you restart it.

**To Reproduce**
1. Open Tools from the menu
2. Select Preferences
3. Select Startup
4. Change the language
5. Restart the program

**Expected behavior**
When the program is restarted, the interface language becomes Russian.

**Screenshots**
![Скриншот 05-03-2021 233623](https://user-images.githubusercontent.com/55694958/110144840-5c1bd500-7e0b-11eb-9eec-029be576cffd.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [1.6.6]

**Additional context**

**Comment by DylanC** [comment]
Dup of #332

**Comment by DylanC** [comment]
Fixed via v1.6.7 release.
