### ISSUE TITLE
Resave and rotate a file

### ISSUE THREAD

**Issue by vladz99** [PhotoFlare/photoflare#435]
**Describe the bug**
When using "Automate / Batch" "Image Size", the application resaves the original file and rotates it 90 degrees.

**To Reproduce**

1. Select "Tools"
2. Select "Automate/Batch"
3. Open the image
4. Click "Image Size"
5. Check the box "Image Size"
6. Change the size
7. Click "OK"

**Expected behavior**
The program saves the original file along with the new one and does not flip the image.

**Screenshots**
![Скриншот 07-03-2021 000255](https://user-images.githubusercontent.com/55694958/110214661-36a8cd00-7ed8-11eb-8cde-5ceed214bf47.jpg)
![Скриншот 07-03-2021 000304](https://user-images.githubusercontent.com/55694958/110214664-390b2700-7ed8-11eb-84db-52b9951dc273.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [1.6.6]

**Additional context**

**Comment by DylanC** [comment]
Dup of #266

**Comment by DylanC** [comment]
Fixed in commit 0f9195fb5fe7e05589ee49195d6c547a725a5be7.
