### ISSUE TITLE
The range from 0 to 1 only changes from 0 to 1

### ISSUE THREAD

**Issue by vladz99** [PhotoFlare/photoflare#436]
**Describe the bug**
When you change the range of arrows from 0 to 1, it only changes from 0 to 1 and back.

**To Reproduce**
1. Open to Image
2. Select "Adjust"
3. Select "Opacity"
4. Click on the arrows

**Expected behavior**
The range changes smoothly.

**Screenshots**
![Скриншот 07-03-2021 000736](https://user-images.githubusercontent.com/55694958/110214804-dc5c3c00-7ed8-11eb-8957-022bfc86697b.jpg)
![Скриншот 07-03-2021 000741](https://user-images.githubusercontent.com/55694958/110214805-de25ff80-7ed8-11eb-8ca6-8c89799a6ae9.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [1.6.6]

**Additional context**

**Comment by DylanC** [comment]
Dup of #286
