### ISSUE TITLE
When batch loading images are flipped over

### ISSUE THREAD

**Issue by vladz99** [PhotoFlare/photoflare#437]
**Describe the bug**
When batch loading images are flipped over.

**To Reproduce**
1. Select "Tools"
2. Select "Automate/Batch"
3. Add 2 images
4. Click "Ok"

**Expected behavior**
Images are loaded in normal form, not flipped

**Screenshots**
![Скриншот 07-03-2021 001313](https://user-images.githubusercontent.com/55694958/110214953-ac616880-7ed9-11eb-8050-488c3469dc5b.jpg)
![Скриншот 07-03-2021 001322](https://user-images.githubusercontent.com/55694958/110214954-b1beb300-7ed9-11eb-9b9d-b5d5d00cf99b.jpg)
![Скриншот 07-03-2021 001328](https://user-images.githubusercontent.com/55694958/110214957-b7b49400-7ed9-11eb-8e83-440d5535bb0c.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [1.6.6]

**Additional context**

**Comment by DylanC** [comment]
Dup of #266

**Comment by DylanC** [comment]
Fixed in commit 0f9195fb5fe7e05589ee49195d6c547a725a5be7.
