### ISSUE TITLE
Stripes appear in the image when you correct the light and contrast of the image

### ISSUE THREAD

**Issue by AnastasiaDyadyk** [PhotoFlare/photoflare#448]
If you correct the brightness, contrast, saturation, gamma correct, dust reduction on the image, horizontal stripes appear on the image, spoiling the image.

1. Open / create an image
2. Click on «brightness»/ «contrast»/ «saturation»/ « gamma correct/ « dust reduction» several times.

Expected Behavior: Image correction is in progress, image quality is not degraded.
![3](https://user-images.githubusercontent.com/80753690/111470708-ba757b80-875a-11eb-830a-a05e0511b735.png)
![4](https://user-images.githubusercontent.com/80753690/111470714-bc3f3f00-875a-11eb-8122-4cda4e0c8995.png)

OS: Windows 10
 Version 1.6.7

**Comment by DylanC** [comment]
Dup of #396

**Comment by DylanC** [comment]
Stripe issue has been fixed in the v1.6.8 release.
https://github.com/PhotoFlare/photoflare/releases/tag/v1.6.8
