### ISSUE TITLE
Stripes in image 

### ISSUE THREAD

**Issue by kandidat-hh** [PhotoFlare/photoflare#451]
1) when trying to convert a 5.82 MB image to "gray scale", "old photography",
"sepia" the program is closed without saving
2) you can't just drag the image to the work area,
opens only through the panel in the application
3) when using a fill on a document 100x100 cm, the program freezes for ~ 30 seconds,
loading the CPU by 25-30%
4) the stripes appear when the image is resized
![4](https://user-images.githubusercontent.com/80974431/111812087-542f5b00-890a-11eb-9b8b-1c1c068e9529.png)
![4 1](https://user-images.githubusercontent.com/80974431/111812054-47ab0280-890a-11eb-881e-625522f260af.JPG)
5) the noise appears in the image when using softness or blur
![5](https://user-images.githubusercontent.com/80974431/111812131-5ee9f000-890a-11eb-9399-86846ebee08f.JPG)
6) when processing a 2.52 MB image in "gray scale", "old photo",
"sepia", extraneous horizontal lines appear

**Comment by DylanC** [comment]
Dup of #396

**Comment by DylanC** [comment]
Stripe issue has been fixed in the v1.6.8 release.
https://github.com/PhotoFlare/photoflare/releases/tag/v1.6.8
