### ISSUE TITLE
Missing russian translation

### ISSUE THREAD

**Issue by AKotov-dev** [PhotoFlare/photoflare#452]
**Describe the bug**
Photoflare-v1.6.7

Hello. In the file Photoflare.pro missing line for russian translation:  
https://github.com/AKotov-dev/photoflare-rpm/blob/main/1.6.7/russian-translation-1.6.7.patch

**To Reproduce**
1. qmake Photoflare.pro
2. ls ./languages | grep ru_RU.qm

**Desktop (please complete the following information):**
 - OS: Mageia Linux 8

**Comment by DylanC** [comment]
@AKotov-dev - Thanks. Pushed a fix fbf7e24173c5410209c4f60834b1041fe45b776b.

**Comment by DylanC** [comment]
Fixed in https://github.com/PhotoFlare/photoflare/releases/tag/v1.6.7.1
