### ISSUE TITLE
Hiding toolpalette should also hide the brush options

### ISSUE THREAD

**Issue by wavexx** [PhotoFlare/photoflare#455]
**Describe the bug**
I tried to hide the toolpalette (via Ctrl+L) to save some space while previewing an image. However I was surprised to see that the right side of the dock didn't shrink.

I later discovered that there's a second toolbar in there, where the brush options are shown, which is what prevents the dock from shrinking.

I don't think it's valuable to just hide the toolpalette if the aim is to free up screen space.

**To Reproduce**
1. Start Photoflare
2. View->Toolpalette (or Ctrl+L)
3. Right dock doesn't really disappear, although it _looks_ empty.

**Expected behavior**
The dock should shrink when the toolpalette is hidden. Hiding both the toolpalette and brush options at the same time makes sense to me, without introducing a new checkbox to toggle the visibility of the brush settings.

**Desktop (please complete the following information):**
 - OS: Linux (debian unstable)
 - Version: 1.6.6

**Comment by DylanC** [comment]
@wavexx - That makes sense. Thanks! 👍
