### ISSUE TITLE
Language selection not working

### ISSUE THREAD

**Issue by othias** [PhotoFlare/photoflare#458]
Hello, I just built 1.6.7.1 from source, everything works but language selection doesn't seem to have any effect. the 'languages' directory is next to the photoflare binary. I have also tried copying the languages directory to /usr/share/photoflare/Photoflare/ but still not working :S no errors shown in the console output either. Any idea ? Thanks

**Comment by AKotov-dev** [comment]
Hi, othias.  

It looks like this to me:
`mkdir 111 && cd ./111 && wget https://github.com/PhotoFlare/photoflare/archive/refs/tags/v1.6.7.1.tar.gz && tar xvzf ./*.tar.gz && cd ./photo* && qmake && make install`
...
/usr/bin/qmake -install qinstall /111/111/photoflare-1.6.7.1/111/photoflare-1.6.7.1/languages/en.qm /usr/local/share/photoflare/languages/en.qm
/usr/bin/qmake -install qinstall /111/111/photoflare-1.6.7.1/111/photoflare-1.6.7.1/languages/fr.qm /usr/local/share/photoflare/languages/fr.qm
...

You do a `qmake` before the `make install` to get the translation files `.qm`?

Additional link to rpm packages for Mageia Linux (if applicable): https://github.com/AKotov-dev/photoflare-rpm

Sincerely, Alex

**Comment by othias** [comment]
Thanks Alex, I copied the languages directory in /usr/local/share/photoflare and it works fine, thanks !
