### ISSUE TITLE
Drawing performance regression in 1.6.9

### ISSUE THREAD

**Issue by omgbebebe** [PhotoFlare/photoflare#463]
**Describe the bug**
Updating the canvas is very slow.

**To Reproduce**
1. start photoflare of version 1.6.9
2. create a new document with default parameters
3. zoom to the maximum level with mouse scroll
4. select a drawing tool, i.e. advanced paint brush, try to pain something
5. canvas updates will be very slow

**Expected behavior**
Canvas updating without any noticeable lags

**Desktop (please complete the following information):**
 - Linux
 - 1.6.9

**Additional context**
Looks like a regression somewhere in between 1.6.8 and 1.6.9.

**Comment by DylanC** [comment]
@omgbebebe - Thanks for the report. We will investigate. 👍

**Comment by mastersin** [comment]
There is only one suspicious commit e664f48d616fa37ad4fab3c453aa958bee277c28 and that's it is.
I reverted the commit to fix this problem.

**Comment by DylanC** [comment]
@mastersin - Thanks for investigating. 👍  That's a shame as I really like the drop shadow effect. Maybe there is a better performance way to achieve this. 🤔
