### ISSUE TITLE
Unlock Ratio in Resize Canvas

### ISSUE THREAD

**Issue by wizetek** [PhotoFlare/photoflare#468]
I'd like to have the ability to decouple (unlock ratio) the _Width_ and _Height_ fields in _Resize Canvas_ just like it's already possible in the _Resize Image_ dialog.

Say, I'm working with an image dimensions 2560x1600 which I'd like to crop to fit my display 2560x1440. It would be effortless to simply reduce 1600 to 1440 and then specify the preferred _Position_.

Using v1.6.9 on Arch Linux here. Thanks for all your work and for considering to implement this.

**Comment by DylanC** [comment]
@wizetek - This is a good idea. Thanks!

**Comment by DylanC** [comment]
@wizetek - I have this added for the next release. 👍

**Comment by wizetek** [comment]
Excellent! I'm looking forward to testing it and using this feature. No more switching to "the other app" only for this one purpose. Thank you very much.
