### ISSUE TITLE
Version comparison doesn't work?

### ISSUE THREAD

**Issue by AKotov-dev** [PhotoFlare/photoflare#470]
Hello **DylanC**. The latest version is installed - v1.6.10 (Mageia Linux-8, x86_64). If you check for updates: `Help->Check for Updates`, then it is reported that there is an even newer version and it is suggested to download it. Version comparison doesn't work?

Sincerely,
Alex

**Comment by DylanC** [comment]
Hi @AKotov-dev, Thanks for the report.

Yes. Something here is wrong. I'll investigate! 👍
