### ISSUE TITLE
Opening an invalid image file results in empty tab

### ISSUE THREAD

**Issue by nerdouille** [PhotoFlare/photoflare#64]
Trying to open any non-image file (.txt or whatever), results in an empty tab being opened in photoflare, with no indication that the file is not an image file. Perhaps an error message would be more appropriate?

Tested on both windows and debian linux.

**Comment by DylanC** [comment]
@nerdouille - Yes, I don't know why but I never tried this before. :)

**Comment by DylanC** [comment]
Hi @nerdouille - I've added a fix for this (20b68c4aae0305e2699e1e10506aa0bd86fdb3f9). Now the empty tab will not appear and we show an error message instead.

**Comment by DylanC** [comment]
Translations need to be updated but closing this as complete for now.

**Comment by nerdouille** [comment]
Thanks :)
