### ISSUE TITLE
Photoflare V1.5.1 release date for ubuntu/debian based 16.04 ?

### ISSUE THREAD

**Issue by orion777** [PhotoFlare/photoflare#73]
Hello

We work on linuxmint 18.3 based on ubuntu 16.04 but we can't get the new updating photoflare V1.5.1 because it is only for ubuntu based 17.10.
Any date for this release? thanks you very much.

**Comment by DylanC** [comment]
@orion777 - Hello. There is a problem with the Linux Mint VM on the build server. Looking into this issue at the moment. Maybe check here again on the weekend and it may be solved.

I will update you with news sooner if we have progress.

**Comment by DylanC** [comment]
@orion777 - Hello, This download is now available from our downloads page:
http://photoflare.io/downloads/

Direct link:
https://launchpad.net/photofiltre-lx/trunk/v1.5.1/+download/PhotoFlare_CE_1.5.1_amd64_xenial.deb

**Comment by orion777** [comment]
Thanks you very much!!
We are working in a school and looking for a an alternative of Photofiltre on Linuxmint.
Will you add more tools in the toolbox like photofiltre?
We noticed some problems with the toolbox display when using different screen resolution.
Thanks you for your help and for this great project for linux.

Regards

**Comment by DylanC** [comment]
@orion777 - No problem. Can you tell me what tools you need in the toolbox? Also please tell us the screen resolutions that give you trouble. Thanks.

**Comment by orion777** [comment]
OK so we have trouble with 16:9 screen display and screen with 1024x768 screen ratio resolution.
The problem is with the part of the toolbox with the eraser tool. Take a look on the screen capture
As you can see when launching photoflare we can't select the eraser tool and the other tools next the eraser tool because of the resolution displaying.
This capture is taken on a 16:10 screen display resolution 1024x768 Linuxmint 1
Thanks you very much for your great help.
![capture d ecran_2018-03-09_13-20-45](https://user-images.githubusercontent.com/29846901/37207507-a59f0df8-239d-11e8-8cb9-64c670d54ed9.png)

**Comment by orion777** [comment]
We have to reduce the windows display to have the tools enabled.

**Comment by orion777** [comment]
Please can you add more filters like photofilter, and layer option (fusion ..) and more settings option.
In the toolbox can you add more selector tools like the screen capture below.
Thanks you very much for your job
![capture d ecran_2018-03-09_13-42-25](https://user-images.githubusercontent.com/29846901/37207971-cdc109ba-239f-11e8-9db9-354f77e39d45.png)

**Comment by DylanC** [comment]
@orion777 - Thanks very much for this information. I will add some separate issues for each item to be worked on.
