### ISSUE TITLE
Improve tool settings display/layout on smaller resolution screens

### ISSUE THREAD

**Issue by DylanC** [PhotoFlare/photoflare#75]
Screen resolution of 1024x768 causing issues displaying the tool settings/tools and some tools cannot be clicked on.

**Comment by orion777** [comment]
Hello

Is this issue fixed?
Regards

**Comment by orion777** [comment]
If this issue is fixed is it possible to provide latest photoflare version for linuxmint 18.3 ? This was the biggest issue here. We will use Linuxmint 18.3 in our school until 2020-21.
Thanks you for your help
Regards

**Comment by DylanC** [comment]
@orion777 - This issue should be fixed now. I am working on a package for 16.04/Mint 18.3 at the moment.

**Comment by orion777** [comment]
Thanks you very much. I am following with interest the photoflare version progress.
Hope to get the best complete version for our teachers and students here on Mint 18.3.
