### ISSUE TITLE
Please remove *.ai resources or provide alternative tarball without them?

### ISSUE THREAD

**Issue by mmetak** [PhotoFlare/photoflare#81]
Hello, I maintain `photoflare` and `photoflare-git` packages for archlinux in aur and I was wondering if it would be possible to provide tarball without the *.ai assets?
For package maintainers they're useless and just increase tarball size to 50MB.

Thanks.

**Comment by DylanC** [comment]
@mmetak - Good idea! I have them removed now! Its the same src as the 1.5.3 release just without the .ai files.
