### ISSUE TITLE
Wrong version of .deb in automatic download for Debian 9

### ISSUE THREAD

**Issue by anechampenois** [PhotoFlare/photoflare#82]
On the PhotoFlare website, when I tried to download PF, it leads to [https://launchpad.net/photofiltre-lx/trunk/v1.5.3/+download/PhotoFlare_CE_1.5.3_amd64_17.10.deb](url)
After downloading and installing it (without any error from Gdebi), PhotoFlare doesn't launch at all (error of compatibility for Qt libraries, says my terminal).
I've tested [https://launchpad.net/photofiltre-lx/trunk/v1.5.3/+download/PhotoFlare_CE_1.5.3_amd64_16.04.deb](url) from the downloaded page, and it works perferctly.
So 2 enhancements are needed:

1. changing the version automatically downloaded when somebody with a Debian 9 (Stretch, the current stable version of Debian) tries to download directly.

2. Adding an information on the page [https://photoflare.io/downloads/](url) like this (addition ** **): 
```
Ubuntu/Debian Based
17.10
PhotoFlare_CE_1.5.3_amd64_17.10.deb (64bit)
PhotoFlare_CE_1.5.3_i386_17.10.deb (32bit)
16.04/Linux Mint 18 **/ Debian 9**
PhotoFlare_CE_1.5.3_amd64_16.04.deb (64bit)
arch
```

Thanks for your great  work. :+1:

**Comment by DylanC** [comment]
@anechampenois - Thanks for this information. I will solve this as soon as possible. :)

**Comment by anechampenois** [comment]
for me, the second point is okay but not the first one...but perhaps can't you/won't you change it?
Anyway there's a workaround now.

**Comment by DylanC** [comment]
@anechampenois - I did change the first one but I don't have Debian OS to test this. I have set the debian download button to download the 16.04 installer. I will have another look at this. o_O

**Comment by DylanC** [comment]
@anechampenois - Can you send me a screenshot of the button on the homepage you are using?

**Comment by anechampenois** [comment]
@DylanC here it is: [https://framapic.org/9jQo4d4bb9Lp/d4ojTfqNZxxL.png](url)
Note that the same problem exists with the 64bits version (the button says "Download 64 bit" and the downloading version is the 17.10 amd64 .deb version) as I've tested on my second computer (Debian 9 64 bit)

**Comment by DylanC** [comment]
@anechampenois - Oh I see now. That is the general Linux button and not the Debian one. Seems your OS is detecting as just Linux.  What browser do you use on Debian?

**Comment by anechampenois** [comment]
I use Firefox (v 59.0.2 ATM) but this is not the version distributed by Debian itself but a personal install from Mozilla's repositories for my 2 computers. Perhaps it has an effect on your detection...

**Comment by anechampenois** [comment]
@DylanC do you need some testing? I can use a vanilla Debian 9 install with Firefox from Debian repositories to test if the same proble exists.

**Comment by DylanC** [comment]
@anechampenois - Its okay, I can test the vanilla Debian 9 today. I have a .iso downloading at the moment. I will let you know if that problem is with the vanilla or only Firefox from Mozilla repo. :)

**Comment by DylanC** [comment]
Oh right. It seems the browser doesn't tell us that its Debian even with vanilla Firefox. I'm not sure there is anything much I can do.

**Comment by DylanC** [comment]
@anechampenois - I hope you don't mind me closing this. I think I have done as much as I can for it.

**Comment by anechampenois** [comment]
@DylanC It's ok for me, you've done your best. If I have a little time in the 3 next weeks, I take a look at it to see if there's a better way to do or perhaps posting a bug report on Debian's site.

**Comment by anechampenois** [comment]
@DylanC According to what I've found:

- there's no user agent specific to Debian, either on Chromium or Firefox

- here's  a  list of  [user agents commonly used in 2018](https://techblog.willshouse.com/2012/01/03/most-common-user-agents/)
With these informations, you can adapt the code of photoflare.io on the detection of the user agent part. I can't do it myself...
If I were you, either I disabled this detection because it could be confusing (eg: LinuxMint uses an 'Ubuntu' user agent...and not a specific one) and leads to installing a wrong version witch doesn't work, or you have to strongly modify user agent detection (eg: on Windows, some browser use 'WOW' and no Win...)

**Comment by DylanC** [comment]
@anechampenois - Once Linux Mint 19 is released both Ubuntu and Mint users can install the 18.04 .deb. This should resolve the problem for most people. Hopefully Debian will be able to install the 18.04 .deb soon too.
