### ISSUE TITLE
Turn on/off the full screen mode and the window title and the control buttons were disappear

### ISSUE THREAD

**Issue by bogdanov-da** [PhotoFlare/photoflare#88]
1. Run the program 
2. Go to "View"
3. Press "Full Screen" - window title and control buttons are not available
4. Click "Full Screen" again.

We are waiting for the title and buttons to become available but they are not. The program window can not be moved after press the full screen mode.

Environment: Win 10, 64x. PhotoFlare v.1.5.3

**Comment by DylanC** [comment]
@bogdanov-da - Yes... another bug. Thanks again! :laughing: :+1:

**Comment by DylanC** [comment]
Fixed in source.
