### ISSUE TITLE
The program stops working if you try to open a file without an extension

### ISSUE THREAD

**Issue by bogdanov-da** [PhotoFlare/photoflare#89]
0. Prepare a file without extension (file type in Windows is "File")
1. Run the program 
2. Press "Ctrl+O"
3. Select the file from p. 0 and press "Open"

We expect message "Please open a valid image file" but the program is closed by Windows with system error message.

**Comment by DylanC** [comment]
@bogdanov-da - Hello, I've tested this on Windows 10 (64bit) and I do see the Error message. Do you have any more details to help me reproduce this issue?
