### ISSUE TITLE
Get Travis CI running

### ISSUE THREAD

**Issue by DylanC** [PhotoFlare/photoflare#9]
It would be handy to have Travis CI running on 16.04 Ubuntu as the platform if possible.

**Comment by Dean-Coakley** [comment]
Can we look at running Jenkins instead perhaps. Unfortunately this would have to be self hosted but could probably run on a 10$/month droplet on Digital Ocean. Benefit of this is we can run the build on a native 16.04 instance so this would cut out the Docker config step. - Let me know.
