### ISSUE TITLE
The question mark does not provide background information

### ISSUE THREAD

**Issue by bogdanov-da** [PhotoFlare/photoflare#91]
1. Run the program
2. Open any dialog window (eg. Image->Image Size)
3. Press on question mark and direct on any element on the window.
We expect that there will be information about elements but it's not there.
Environment: Win 10, 64x. PhotoFlare v.1.5.3

**Comment by DylanC** [comment]
@bogdanov-da - This is just to show the Help menu. Its not a Tutorial feature.

**Comment by DylanC** [comment]
This is more of an enhancement really as we never planned on this feature. Need to use this on our widgets to populate the text on items:
http://doc.qt.io/qt-5/qwhatsthis.html

**Comment by DylanC** [comment]
@bogdanov-da - Since it wasn't intended as something to add I will just be removing it from the next version. b6abc38bb2d1b36f07af09296c7ede690e4d3bfd
