### ISSUE TITLE
Incorrect header on change language button in Dutch language version

### ISSUE THREAD

**Issue by bogdanov-da** [PhotoFlare/photoflare#92]
0. Choose Dutch in program language
1. Run the program
2. Go to Gereedschappen->Voorkeugen->Opstarten
3. Choose any language (not Dutch) - button for restart has incorrect header ->https://ibb.co/kW3nio
Environment: Win 10, 64x. PhotoFlare v.1.5.3

**Comment by DylanC** [comment]
@bogdanov-da - What do you expect to see in this case?
