### ISSUE TITLE
The maximize window option is not applied

### ISSUE THREAD

**Issue by bogdanov-da** [PhotoFlare/photoflare#93]
1. Run the program
2. Go to Tools->Preferences->Startup
3. Check "Maximize on Startup"
4. Close the program
5. Run the program - window in maximum resolution
6. Close the program 
7. Run the program - window in normal resolution
We expect that after the option of maximize is enabled, the program window will always be at the maximum resolution.
Environment: Win 10, 64x. PhotoFlare v.1.5.3

**Comment by DylanC** [comment]
@bogdanov-da - Yep, this is bug. However, its fixed in the code. 8d00970f2f97e84396fe9a3cf67f484dc96db11b
