### ISSUE TITLE
File converting does not work in Automate/Batch

### ISSUE THREAD

**Issue by bogdanov-da** [PhotoFlare/photoflare#95]
1. Run the program
2. Click om Automate/Batch icon - Automate/Batch window is opened
3. Add new picture in png format
4. Choose output folder and output format gif or jpg, click OK
New file is created in output folder but it format is png.
Environment: Win 10, 64x. PhotoFlare v.1.5.3

**Comment by DylanC** [comment]
@bogdanov-da - Confirmed as a bug. Thanks.

**Comment by DylanC** [comment]
Fixed in source.
