### ISSUE TITLE
Program is crashed when we are close select window in Automate/Batch form

### ISSUE THREAD

**Issue by bogdanov-da** [PhotoFlare/photoflare#96]
1. Run the program
2. Click Automate/Batch icon - Automate/Batch window is opened
3. Click on Add files - select files window is opened
4. Close select files window - we see system error message, program is closed
Environment: Win 10, 64x. PhotoFlare v.1.5.3

**Comment by DylanC** [comment]
@bogdanov-da - Yes, confirmed as a bug. Thanks.

**Comment by DylanC** [comment]
Fixed in source.
