### ISSUE TITLE
Different values of the minimum level of compression

### ISSUE THREAD

**Issue by bogdanov-da** [PhotoFlare/photoflare#99]
1. Run the program
2. Go to preferences->Compression - we see that minimal level of compression is 0 - https://ibb.co/kYN6b8
3. Add new file and save it in jpg format - we see that minimal level of compression is 10 - https://ibb.co/fvBPw8
Environment: Win 10, 64x. PhotoFlare v.1.5.3

**Comment by DylanC** [comment]
@bogdanov-da - That compression works in the background. You don't see it if you use show the dialog option. The dialog always shows 90 for me if I'm enabling always show dialog. I can't reproduce this issue unfortunately.
